import Foundation

extension ConversationDataService {
    static let brBeginner: [ConversationScenario] = [
        .init(situation: "At a café", prompt: "Bom dia! O que você quer tomar?", instruction: "Say you want a coffee, please", answer: "Eu quero um café, por favor", alternates: ["Quero um café, por favor", "Um café, por favor"], difficulty: .beginner),
        .init(situation: "Meeting someone", prompt: "Oi! Como você se chama?", instruction: "Say your name (use 'Ana')", answer: "Eu me chamo Ana", alternates: ["Me chamo Ana", "Meu nome é Ana"], difficulty: .beginner),
        .init(situation: "Greeting", prompt: "Tudo bem?", instruction: "Say everything is fine, thanks", answer: "Tudo bem, obrigado", alternates: ["Tudo bem, obrigada", "Tudo bom", "Tudo bem"], difficulty: .beginner),
        .init(situation: "Asking directions", prompt: "Onde fica o supermercado?", instruction: "Say it's on the right", answer: "Fica à direita", alternates: ["É à direita", "Está à direita"], difficulty: .beginner),
        .init(situation: "Restaurant", prompt: "Você já escolheu?", instruction: "Say you want the chicken, please", answer: "Eu quero o frango, por favor", alternates: ["Quero o frango, por favor", "Vou querer o frango"], difficulty: .beginner),
        .init(situation: "At the store", prompt: "Posso ajudar?", instruction: "Say you are looking for a book", answer: "Estou procurando um livro", alternates: ["Eu estou procurando um livro", "Procuro um livro"], difficulty: .beginner),
        .init(situation: "Taxi", prompt: "Para onde vai?", instruction: "Say you're going to the airport", answer: "Vou para o aeroporto", alternates: ["Eu vou para o aeroporto", "Para o aeroporto, por favor"], difficulty: .beginner),
        .init(situation: "Phone call", prompt: "Alô, quem fala?", instruction: "Say it's you (use 'João')", answer: "É o João", alternates: ["Sou o João", "Aqui é o João"], difficulty: .beginner),
        .init(situation: "Introductions", prompt: "De onde você é?", instruction: "Say you are from the United States", answer: "Eu sou dos Estados Unidos", alternates: ["Sou dos Estados Unidos", "Sou americano"], difficulty: .beginner),
        .init(situation: "At a bar", prompt: "O que você vai beber?", instruction: "Say you want a juice", answer: "Quero um suco, por favor", alternates: ["Eu quero um suco", "Um suco, por favor"], difficulty: .beginner),
        .init(situation: "Shopping", prompt: "Quanto custa isso?", instruction: "Say it costs ten reais", answer: "Custa dez reais", alternates: ["São dez reais", "Dez reais"], difficulty: .beginner),
        .init(situation: "Time", prompt: "Que horas são?", instruction: "Say it is three o'clock", answer: "São três horas", alternates: ["Três horas"], difficulty: .beginner),
        .init(situation: "Weather", prompt: "Como está o tempo hoje?", instruction: "Say it is hot today", answer: "Está quente hoje", alternates: ["Hoje está quente", "Faz calor hoje"], difficulty: .beginner),
        .init(situation: "At home", prompt: "Você tem irmãos?", instruction: "Say you have one brother", answer: "Tenho um irmão", alternates: ["Eu tenho um irmão", "Sim, tenho um irmão"], difficulty: .beginner),
        .init(situation: "Daily routine", prompt: "A que horas você acorda?", instruction: "Say you wake up at seven", answer: "Eu acordo às sete", alternates: ["Acordo às sete", "Às sete horas"], difficulty: .beginner),
        .init(situation: "Restaurant", prompt: "A conta, por favor.", instruction: "Say thank you very much", answer: "Muito obrigado", alternates: ["Muito obrigada", "Obrigado"], difficulty: .beginner),
        .init(situation: "Market", prompt: "Você quer mais alguma coisa?", instruction: "Say no, that's all, thanks", answer: "Não, é só isso, obrigado", alternates: ["Não, obrigado", "É só, obrigado"], difficulty: .beginner),
        .init(situation: "Asking age", prompt: "Quantos anos você tem?", instruction: "Say you are twenty-five years old", answer: "Tenho vinte e cinco anos", alternates: ["Eu tenho vinte e cinco anos"], difficulty: .beginner),
        .init(situation: "Professions", prompt: "O que você faz?", instruction: "Say you are a student", answer: "Eu sou estudante", alternates: ["Sou estudante"], difficulty: .beginner),
        .init(situation: "Likes", prompt: "Você gosta de futebol?", instruction: "Say yes, you like it a lot", answer: "Sim, eu gosto muito", alternates: ["Gosto muito", "Sim, gosto muito de futebol"], difficulty: .beginner),
        .init(situation: "Pharmacy", prompt: "O que você precisa?", instruction: "Say you need medicine", answer: "Preciso de remédio", alternates: ["Eu preciso de remédio", "Preciso de um remédio"], difficulty: .beginner),
        .init(situation: "Bus", prompt: "Esse ônibus vai para o centro?", instruction: "Say yes, it does", answer: "Sim, vai", alternates: ["Vai sim", "Sim, esse vai"], difficulty: .beginner),
        .init(situation: "Hotel", prompt: "Tem quarto disponível?", instruction: "Say you want a room for two nights", answer: "Quero um quarto para duas noites", alternates: ["Um quarto para duas noites, por favor"], difficulty: .beginner),
        .init(situation: "Colors", prompt: "De que cor é sua camisa?", instruction: "Say your shirt is blue", answer: "Minha camisa é azul", alternates: ["É azul", "A minha camisa é azul"], difficulty: .beginner),
        .init(situation: "Numbers", prompt: "Qual é o seu número de telefone?", instruction: "Say you don't have a phone", answer: "Eu não tenho telefone", alternates: ["Não tenho telefone"], difficulty: .beginner),
        .init(situation: "Days of the week", prompt: "Que dia é hoje?", instruction: "Say today is Monday", answer: "Hoje é segunda-feira", alternates: ["É segunda-feira", "Segunda-feira"], difficulty: .beginner),
        .init(situation: "Food", prompt: "Você gosta de arroz e feijão?", instruction: "Say yes, you love it", answer: "Sim, eu adoro", alternates: ["Adoro", "Sim, adoro arroz e feijão"], difficulty: .beginner),
        .init(situation: "Bathroom", prompt: "Onde fica o banheiro?", instruction: "Say it's over there on the left", answer: "Fica ali à esquerda", alternates: ["Ali à esquerda", "É ali à esquerda"], difficulty: .beginner),
        .init(situation: "Family", prompt: "Como é a sua família?", instruction: "Say your family is big", answer: "Minha família é grande", alternates: ["A minha família é grande"], difficulty: .beginner),
        .init(situation: "Pets", prompt: "Você tem animais de estimação?", instruction: "Say you have a dog", answer: "Tenho um cachorro", alternates: ["Eu tenho um cachorro", "Sim, tenho um cachorro"], difficulty: .beginner),
        .init(situation: "School", prompt: "Onde você estuda?", instruction: "Say you study at the university", answer: "Estudo na universidade", alternates: ["Eu estudo na universidade"], difficulty: .beginner),
        .init(situation: "Goodbye", prompt: "Tchau! Até amanhã!", instruction: "Say goodbye, see you tomorrow", answer: "Tchau! Até amanhã!", alternates: ["Até amanhã", "Tchau"], difficulty: .beginner),
        .init(situation: "Asking for help", prompt: "Você pode me ajudar?", instruction: "Say yes, of course", answer: "Sim, claro", alternates: ["Claro", "Claro que sim"], difficulty: .beginner),
        .init(situation: "Transport", prompt: "Como você vai para o trabalho?", instruction: "Say you go by bus", answer: "Vou de ônibus", alternates: ["Eu vou de ônibus"], difficulty: .beginner),
        .init(situation: "Compliment", prompt: "Sua casa é muito bonita!", instruction: "Say thank you", answer: "Obrigado", alternates: ["Obrigada", "Muito obrigado"], difficulty: .beginner),
        .init(situation: "Menu", prompt: "Vocês têm pizza?", instruction: "Say no, only pasta", answer: "Não, só temos massa", alternates: ["Não, só massa"], difficulty: .beginner),
        .init(situation: "Sports", prompt: "Você joga futebol?", instruction: "Say yes, you play every weekend", answer: "Sim, jogo todo fim de semana", alternates: ["Jogo todo fim de semana"], difficulty: .beginner),
        .init(situation: "Hobbies", prompt: "O que você gosta de fazer?", instruction: "Say you like to read", answer: "Gosto de ler", alternates: ["Eu gosto de ler"], difficulty: .beginner),
        .init(situation: "Nationality", prompt: "Você é brasileiro?", instruction: "Say no, you are English", answer: "Não, sou inglês", alternates: ["Não, eu sou inglês", "Não, sou inglesa"], difficulty: .beginner),
        .init(situation: "Drinking", prompt: "Você quer água?", instruction: "Say yes, please", answer: "Sim, por favor", alternates: ["Quero sim, por favor"], difficulty: .beginner),
        .init(situation: "Apology", prompt: "Você pisou no meu pé!", instruction: "Say sorry, excuse me", answer: "Desculpa", alternates: ["Me desculpe", "Desculpe"], difficulty: .beginner),
        .init(situation: "At the beach", prompt: "A água está fria?", instruction: "Say no, it's warm", answer: "Não, está quente", alternates: ["Não, está quentinha", "Está quente"], difficulty: .beginner),
        .init(situation: "Date", prompt: "Qual é a data de hoje?", instruction: "Say today is March 10th", answer: "Hoje é dia dez de março", alternates: ["Dez de março"], difficulty: .beginner),
        .init(situation: "Feelings", prompt: "Como você está?", instruction: "Say you are happy", answer: "Estou feliz", alternates: ["Eu estou feliz"], difficulty: .beginner),
        .init(situation: "Permission", prompt: "Posso entrar?", instruction: "Say yes, come in", answer: "Sim, pode entrar", alternates: ["Pode entrar", "Claro, entra"], difficulty: .beginner),
        .init(situation: "Music", prompt: "Que tipo de música você gosta?", instruction: "Say you like samba", answer: "Gosto de samba", alternates: ["Eu gosto de samba"], difficulty: .beginner),
        .init(situation: "Describing people", prompt: "Como é o seu professor?", instruction: "Say he is tall and nice", answer: "Ele é alto e simpático", alternates: ["É alto e simpático"], difficulty: .beginner),
        .init(situation: "Clothing", prompt: "O que você vai vestir?", instruction: "Say you will wear a dress", answer: "Vou vestir um vestido", alternates: ["Eu vou vestir um vestido"], difficulty: .beginner),
        .init(situation: "Fruit", prompt: "Qual é a sua fruta favorita?", instruction: "Say your favorite fruit is mango", answer: "Minha fruta favorita é manga", alternates: ["É manga", "Manga"], difficulty: .beginner),
        .init(situation: "Language", prompt: "Você fala inglês?", instruction: "Say yes, you speak English and Portuguese", answer: "Sim, falo inglês e português", alternates: ["Falo inglês e português"], difficulty: .beginner),
        .init(situation: "Address", prompt: "Qual é o seu endereço?", instruction: "Say you live on Main Street", answer: "Moro na Rua Principal", alternates: ["Eu moro na Rua Principal"], difficulty: .beginner),
        .init(situation: "Thanking", prompt: "Aqui está o seu troco.", instruction: "Say thank you, have a good day", answer: "Obrigado, tenha um bom dia", alternates: ["Obrigada, tenha um bom dia", "Obrigado, bom dia"], difficulty: .beginner),
        .init(situation: "Repeating", prompt: "O quê? Não entendi.", instruction: "Say please repeat more slowly", answer: "Por favor, repita mais devagar", alternates: ["Pode repetir mais devagar?", "Repita, por favor"], difficulty: .beginner),
        .init(situation: "Breakfast", prompt: "O que você come no café da manhã?", instruction: "Say you eat bread and butter", answer: "Como pão com manteiga", alternates: ["Eu como pão com manteiga"], difficulty: .beginner),
        .init(situation: "Weekend", prompt: "O que você faz no fim de semana?", instruction: "Say you go to the park", answer: "Vou ao parque", alternates: ["Eu vou ao parque"], difficulty: .beginner),
    ]
}
