import Foundation

extension ConversationDataService {
    static let ptBeginner: [ConversationScenario] = [
        .init(situation: "At a café", prompt: "Bom dia! O que deseja?", instruction: "Say you want a coffee, please", answer: "Quero um café, por favor", alternates: ["Eu quero um café, por favor", "Um café, se faz favor"], difficulty: .beginner),
        .init(situation: "Meeting someone", prompt: "Olá! Como te chamas?", instruction: "Say your name (use 'Ana')", answer: "Chamo-me Ana", alternates: ["O meu nome é Ana", "Eu chamo-me Ana"], difficulty: .beginner),
        .init(situation: "Greeting", prompt: "Está bom?", instruction: "Say everything is fine, thanks", answer: "Está tudo bem, obrigado", alternates: ["Está tudo bem, obrigada", "Tudo bem", "Está bom, obrigado"], difficulty: .beginner),
        .init(situation: "Asking directions", prompt: "Onde fica o supermercado?", instruction: "Say it's on the right", answer: "Fica à direita", alternates: ["É à direita", "Está à direita"], difficulty: .beginner),
        .init(situation: "Restaurant", prompt: "Já escolheu?", instruction: "Say you want the fish, please", answer: "Quero o peixe, se faz favor", alternates: ["Eu quero o peixe, por favor", "O peixe, se faz favor"], difficulty: .beginner),
        .init(situation: "At the store", prompt: "Posso ajudar?", instruction: "Say you are looking for a book", answer: "Estou à procura de um livro", alternates: ["Procuro um livro", "Estou a procurar um livro"], difficulty: .beginner),
        .init(situation: "Taxi", prompt: "Para onde vai?", instruction: "Say you're going to the airport", answer: "Vou para o aeroporto", alternates: ["Para o aeroporto, se faz favor"], difficulty: .beginner),
        .init(situation: "Phone call", prompt: "Estou? Quem fala?", instruction: "Say it's you (use 'João')", answer: "É o João", alternates: ["Fala o João", "Aqui é o João"], difficulty: .beginner),
        .init(situation: "Age", prompt: "Quantos anos tens?", instruction: "Say you are twenty-five years old", answer: "Tenho vinte e cinco anos", alternates: ["Vinte e cinco"], difficulty: .beginner),
        .init(situation: "Origin", prompt: "De onde és?", instruction: "Say you are from England", answer: "Sou de Inglaterra", alternates: ["Sou inglês", "Sou inglesa"], difficulty: .beginner),
        .init(situation: "Profession", prompt: "O que fazes?", instruction: "Say you are a teacher", answer: "Sou professor", alternates: ["Sou professora"], difficulty: .beginner),
        .init(situation: "Time", prompt: "Que horas são?", instruction: "Say it is two o'clock", answer: "São duas horas", alternates: ["Duas horas"], difficulty: .beginner),
        .init(situation: "Weather", prompt: "Como está o tempo?", instruction: "Say it is cold today", answer: "Está frio hoje", alternates: ["Hoje está frio"], difficulty: .beginner),
        .init(situation: "Family", prompt: "Tens irmãos?", instruction: "Say you have two sisters", answer: "Tenho duas irmãs", alternates: ["Sim, tenho duas irmãs"], difficulty: .beginner),
        .init(situation: "Food", prompt: "Gostas de bacalhau?", instruction: "Say yes, you love it", answer: "Sim, adoro", alternates: ["Adoro bacalhau"], difficulty: .beginner),
        .init(situation: "Shopping", prompt: "Quanto custa isto?", instruction: "Say it costs five euros", answer: "Custa cinco euros", alternates: ["São cinco euros"], difficulty: .beginner),
        .init(situation: "Transport", prompt: "Como vais para o trabalho?", instruction: "Say you go by metro", answer: "Vou de metro", alternates: ["Apanho o metro"], difficulty: .beginner),
        .init(situation: "Bathroom", prompt: "Onde é a casa de banho?", instruction: "Say it's on the left", answer: "É à esquerda", alternates: ["Fica à esquerda"], difficulty: .beginner),
        .init(situation: "Days", prompt: "Que dia é hoje?", instruction: "Say today is Tuesday", answer: "Hoje é terça-feira", alternates: ["É terça-feira"], difficulty: .beginner),
        .init(situation: "Drinks", prompt: "O que queres beber?", instruction: "Say you want water", answer: "Quero água, se faz favor", alternates: ["Água, por favor"], difficulty: .beginner),
        .init(situation: "Hotel", prompt: "Tem quartos vagos?", instruction: "Say you want a room for one night", answer: "Quero um quarto para uma noite", alternates: ["Um quarto para uma noite, se faz favor"], difficulty: .beginner),
        .init(situation: "Goodbye", prompt: "Adeus! Até amanhã!", instruction: "Say goodbye, see you tomorrow", answer: "Adeus! Até amanhã!", alternates: ["Até amanhã"], difficulty: .beginner),
        .init(situation: "Likes", prompt: "Gostas de música?", instruction: "Say yes, you like fado", answer: "Sim, gosto de fado", alternates: ["Gosto muito de fado"], difficulty: .beginner),
        .init(situation: "Apology", prompt: "Pisaste-me no pé!", instruction: "Say sorry", answer: "Desculpa", alternates: ["Peço desculpa"], difficulty: .beginner),
        .init(situation: "Permission", prompt: "Posso entrar?", instruction: "Say yes, come in", answer: "Sim, pode entrar", alternates: ["Entra", "Pode entrar"], difficulty: .beginner),
        .init(situation: "Help", prompt: "Podes ajudar-me?", instruction: "Say yes, of course", answer: "Sim, claro", alternates: ["Claro que sim"], difficulty: .beginner),
        .init(situation: "Feelings", prompt: "Como estás?", instruction: "Say you are well, thanks", answer: "Estou bem, obrigado", alternates: ["Bem, obrigado", "Estou bem, obrigada"], difficulty: .beginner),
        .init(situation: "Colors", prompt: "De que cor é o teu carro?", instruction: "Say your car is white", answer: "O meu carro é branco", alternates: ["É branco"], difficulty: .beginner),
        .init(situation: "Sports", prompt: "Jogas futebol?", instruction: "Say yes, every Saturday", answer: "Sim, todos os sábados", alternates: ["Jogo todos os sábados"], difficulty: .beginner),
        .init(situation: "Study", prompt: "Onde estudas?", instruction: "Say you study at the University of Lisbon", answer: "Estudo na Universidade de Lisboa", alternates: ["Na Universidade de Lisboa"], difficulty: .beginner),
        .init(situation: "Market", prompt: "Queres mais alguma coisa?", instruction: "Say no, that's all", answer: "Não, é tudo", alternates: ["É só, obrigado"], difficulty: .beginner),
        .init(situation: "Pets", prompt: "Tens animais de estimação?", instruction: "Say you have a cat", answer: "Tenho um gato", alternates: ["Sim, tenho um gato"], difficulty: .beginner),
        .init(situation: "Hobbies", prompt: "O que gostas de fazer?", instruction: "Say you like to cook", answer: "Gosto de cozinhar", alternates: ["Eu gosto de cozinhar"], difficulty: .beginner),
        .init(situation: "Breakfast", prompt: "O que comes ao pequeno-almoço?", instruction: "Say you eat toast and jam", answer: "Como torradas com compota", alternates: ["Torradas com compota"], difficulty: .beginner),
        .init(situation: "Weekend", prompt: "O que fazes ao fim de semana?", instruction: "Say you go to the beach", answer: "Vou à praia", alternates: ["Costumo ir à praia"], difficulty: .beginner),
        .init(situation: "Describing", prompt: "Como é a tua professora?", instruction: "Say she is nice and smart", answer: "Ela é simpática e inteligente", alternates: ["É simpática e inteligente"], difficulty: .beginner),
        .init(situation: "Language", prompt: "Falas português?", instruction: "Say a little, you're learning", answer: "Um pouco, estou a aprender", alternates: ["Falo um pouco"], difficulty: .beginner),
        .init(situation: "Nationality", prompt: "És português?", instruction: "Say no, you are French", answer: "Não, sou francês", alternates: ["Não, sou francesa"], difficulty: .beginner),
        .init(situation: "Clothing", prompt: "O que vais vestir?", instruction: "Say you will wear a jacket", answer: "Vou vestir um casaco", alternates: ["Levo um casaco"], difficulty: .beginner),
        .init(situation: "Address", prompt: "Onde moras?", instruction: "Say you live in Porto", answer: "Moro no Porto", alternates: ["Vivo no Porto"], difficulty: .beginner),
        .init(situation: "Fruit", prompt: "Qual é a tua fruta favorita?", instruction: "Say your favorite is orange", answer: "A minha favorita é laranja", alternates: ["É laranja"], difficulty: .beginner),
        .init(situation: "Menu", prompt: "Têm sopa do dia?", instruction: "Say yes, vegetable soup", answer: "Sim, sopa de legumes", alternates: ["Temos sopa de legumes"], difficulty: .beginner),
        .init(situation: "Asking to repeat", prompt: "Não percebi.", instruction: "Say please repeat", answer: "Pode repetir, se faz favor?", alternates: ["Repita, por favor"], difficulty: .beginner),
        .init(situation: "Thanking", prompt: "Aqui está o seu troco.", instruction: "Say thank you, good afternoon", answer: "Obrigado, boa tarde", alternates: ["Obrigada, boa tarde"], difficulty: .beginner),
        .init(situation: "Music", prompt: "Gostas de fado?", instruction: "Say yes, very much", answer: "Sim, gosto muito", alternates: ["Adoro fado"], difficulty: .beginner),
        .init(situation: "Night out", prompt: "Queres sair hoje à noite?", instruction: "Say yes, where do you want to go", answer: "Sim, onde queres ir?", alternates: ["Quero, para onde?"], difficulty: .beginner),
        .init(situation: "Daily routine", prompt: "A que horas jantares?", instruction: "Say you have dinner at eight", answer: "Janto às oito", alternates: ["Às oito horas"], difficulty: .beginner),
        .init(situation: "Cinema", prompt: "Queres ir ao cinema?", instruction: "Say yes, what's showing", answer: "Sim, o que está a dar?", alternates: ["Quero, o que é que está a passar?"], difficulty: .beginner),
        .init(situation: "Books", prompt: "Gostas de ler?", instruction: "Say yes, you read every day", answer: "Sim, leio todos os dias", alternates: ["Gosto, leio todos os dias"], difficulty: .beginner),
        .init(situation: "Numbers", prompt: "Qual é o teu número?", instruction: "Say you'll write it down", answer: "Vou escrever", alternates: ["Eu escrevo"], difficulty: .beginner),
        .init(situation: "Invitation", prompt: "Queres vir jantar a minha casa?", instruction: "Say yes, with pleasure", answer: "Sim, com muito gosto", alternates: ["Com todo o gosto", "Sim, com prazer"], difficulty: .beginner),
        .init(situation: "Politeness", prompt: "Obrigado pela ajuda!", instruction: "Say you're welcome", answer: "De nada", alternates: ["Não há de quê", "De nada, foi um prazer"], difficulty: .beginner),
        .init(situation: "Health", prompt: "Estás constipado?", instruction: "Say yes, you have a cold", answer: "Sim, estou constipado", alternates: ["Sim, estou constipada"], difficulty: .beginner),
        .init(situation: "Compliment", prompt: "A tua casa é muito bonita!", instruction: "Say thank you very much", answer: "Muito obrigado", alternates: ["Obrigada"], difficulty: .beginner),
        .init(situation: "Date", prompt: "Que data é hoje?", instruction: "Say today is the fifth of April", answer: "Hoje é dia cinco de abril", alternates: ["Cinco de abril"], difficulty: .beginner),
    ]
}
