import Foundation

extension VerbGlossaryService {
    static func glossaryReflexive() -> [GlossaryVerb] {
        [
            v("Abandonar-se", "To abandon oneself"), v("Acalmar-se", "To calm down"),
            v("Adaptar-se", "To adapt oneself"), v("Apaixonar-se", "To fall in love"),
            v("Arrepender-se", "To regret"), v("Atrever-se", "To dare"),
            v("Chamar-se", "To be called"), v("Comportar-se", "To behave"),
            v("Concentrar-se", "To concentrate"), v("Conformar-se", "To conform"),
            v("Deitar-se", "To lie down"), v("Dedicar-se", "To dedicate oneself"),
            v("Deparar-se", "To come across"), v("Despedir-se", "To say goodbye"),
            v("Divertir-se", "To have fun"), v("Entregar-se", "To surrender"),
            v("Esforçar-se", "To make an effort"), v("Expressar-se", "To express oneself"),
            v("Interessar-se", "To be interested"), v("Lavar-se", "To wash oneself"),
            v("Lembrar-se", "To remember"), v("Levantar-se", "To get up"),
            v("Mudar-se", "To move (house)"), v("Orgulhar-se", "To be proud"),
            v("Pentear-se", "To comb one's hair"), v("Preocupar-se", "To worry"),
            v("Preparar-se", "To prepare oneself"), v("Queixar-se", "To complain"),
            v("Referir-se", "To refer to"), v("Reunir-se", "To meet/gather"),
            v("Sentar-se", "To sit down"), v("Sentir-se", "To feel"),
            v("Vestir-se", "To get dressed"),
        ]
    }

    static func glossaryExtra() -> [GlossaryVerb] {
        [
            v("Abanar", "To wave/fan"), v("Abdicar", "To abdicate"),
            v("Absorver", "To absorb"), v("Abstenir", "To abstain", true),
            v("Abusar", "To abuse"), v("Acalorar", "To heat up"),
            v("Acarretar", "To entail"), v("Acelerar", "To accelerate"),
            v("Acentuar", "To accentuate"), v("Adiar", "To postpone"),
            v("Administrar", "To administer"), v("Admitir", "To admit"),
            v("Adotar", "To adopt"), v("Adulterar", "To adulterate"),
            v("Afagar", "To caress"), v("Aferir", "To verify/gauge"),
            v("Afixar", "To affix"), v("Afogar", "To drown"),
            v("Aglomerar", "To agglomerate"), v("Agraciar", "To grace"),
            v("Agrupar", "To group"), v("Alargar", "To widen"),
            v("Alarmar", "To alarm"), v("Alfinetar", "To pin/prick"),
            v("Alinhar", "To align"), v("Almejar", "To aspire to"),
            v("Alocar", "To allocate"), v("Amadurecer", "To mature"),
            v("Amamentar", "To breastfeed"), v("Amarrar", "To tie up"),
            v("Ambicionar", "To aspire"), v("Amparar", "To support"),
            v("Ancorar", "To anchor"), v("Anoitecer", "To get dark"),
            v("Antever", "To foresee"), v("Apadrinhar", "To sponsor/godparent"),
            v("Aperfeiçoar", "To perfect"), v("Apetar", "To feel like"),
            v("Apoiar", "To support"), v("Apossar", "To seize"),
            v("Aprimorar", "To enhance"), v("Apurar", "To refine"),
            v("Arbitrar", "To arbitrate"), v("Armazenar", "To store"),
            v("Arquitetar", "To architect"), v("Articular", "To articulate"),
            v("Aspirar", "To aspirate/aspire"), v("Assaltar", "To assault"),
            v("Assar", "To roast"), v("Assessorar", "To advise"),
            v("Assimilar", "To assimilate"), v("Assobiar", "To whistle"),
            v("Atenuar", "To attenuate"), v("Aterrorizar", "To terrorize"),
            v("Atracar", "To dock"), v("Atropelar", "To run over"),
            v("Auxiliar", "To help"), v("Avariar", "To break down"),
            v("Balançar", "To balance/swing"), v("Barrar", "To block"),
            v("Basear", "To base"), v("Bifurcar", "To fork"),
            v("Bombardear", "To bomb"), v("Brotar", "To sprout"),
            v("Burlar", "To circumvent"), v("Caducar", "To expire"),
            v("Camuflar", "To camouflage"), v("Capitular", "To capitulate"),
            v("Caprichar", "To take great care"), v("Catalogar", "To catalog"),
            v("Centralizar", "To centralize"), v("Cifrar", "To encrypt"),
            v("Cimentar", "To cement"), v("Circular", "To circulate"),
            v("Civilizar", "To civilize"), v("Clarificar", "To clarify"),
            v("Climatizar", "To air-condition"), v("Coagir", "To coerce"),
            v("Cochichar", "To whisper"), v("Coincidir", "To coincide"),
            v("Colaborar", "To collaborate"), v("Colidir", "To collide"),
            v("Colonizar", "To colonize"), v("Comandar", "To command"),
            v("Comercializar", "To commercialize"), v("Cometer", "To commit (an act)"),
            v("Compactar", "To compact"), v("Compilar", "To compile"),
            v("Computar", "To compute"), v("Conceber", "To conceive"),
            v("Conceder", "To grant"), v("Conceituar", "To conceptualize"),
            v("Conciliar", "To reconcile"), v("Condicionar", "To condition"),
            v("Confeccionar", "To make/prepare"), v("Configurar", "To configure"),
            v("Confiscar", "To confiscate"), v("Confrontar", "To confront"),
            v("Congelar", "To freeze"), v("Congregar", "To congregate"),
            v("Conspirar", "To conspire"), v("Constar", "To be stated"),
            v("Consumar", "To consummate"), v("Contaminar", "To contaminate"),
            v("Contentar", "To content"), v("Contextualizar", "To contextualize"),
            v("Contornar", "To go around"), v("Convergir", "To converge"),
            v("Convocar", "To convene"), v("Coordenar", "To coordinate"),
            v("Coroar", "To crown"), v("Corresponder", "To correspond"),
            v("Creditar", "To credit"), v("Cristalizar", "To crystallize"),
            v("Crucificar", "To crucify"), v("Customizar", "To customize"),
            v("Debitar", "To debit"), v("Decifrar", "To decipher"),
            v("Decodificar", "To decode"), v("Decretar", "To decree"),
            v("Delinear", "To delineate"), v("Democratizar", "To democratize"),
            v("Demolir", "To demolish"), v("Denominar", "To denominate"),
            v("Depreciar", "To depreciate"), v("Deputar", "To depute"),
            v("Derivar", "To derive"), v("Derrapar", "To skid"),
            v("Desabar", "To collapse"), v("Desabotoar", "To unbutton"),
            v("Desagradar", "To displease"), v("Desamarrar", "To untie"),
            v("Desaprovar", "To disapprove"), v("Desarmar", "To disarm"),
            v("Desenvoltar", "To unwrap"), v("Desequilibrar", "To unbalance"),
            v("Desfazer", "To undo", true), v("Designar", "To designate"),
            v("Deslizar", "To slide"), v("Desmontar", "To disassemble"),
            v("Despachar", "To dispatch"), v("Desperdiçar", "To waste"),
            v("Despejar", "To pour/evict"), v("Desprezar", "To despise"),
            v("Destrancar", "To unlock"), v("Deteriorar", "To deteriorate"),
            v("Determinar", "To determine"), v("Diagnosticar", "To diagnose"),
            v("Digitalizar", "To digitize"), v("Diluir", "To dilute"),
            v("Diminuir", "To diminish"), v("Direcionar", "To direct"),
            v("Dirigir", "To drive/direct"), v("Disciplinar", "To discipline"),
            v("Discriminar", "To discriminate"), v("Discursar", "To give a speech"),
            v("Discutir", "To discuss"), v("Dispensar", "To dispense"),
            v("Dispersar", "To disperse"), v("Dispor", "To dispose", true),
            v("Disseminar", "To disseminate"), v("Dissolver", "To dissolve"),
            v("Distinguir", "To distinguish"), v("Distribuir", "To distribute"),
            v("Diversificar", "To diversify"), v("Dividir", "To divide"),
            v("Divulgar", "To disclose"), v("Documentar", "To document"),
            v("Domesticar", "To domesticate"), v("Dosificar", "To dose"),
            v("Dramatizar", "To dramatize"), v("Drenar", "To drain"),
            v("Duplicar", "To duplicate"), v("Durar", "To last"),
            v("Ecoar", "To echo"), v("Efetivar", "To make effective"),
            v("Eleger", "To elect"), v("Elevar", "To elevate"),
            v("Elogiar", "To praise"), v("Emancipar", "To emancipate"),
            v("Embaraçar", "To embarrass"), v("Embelezar", "To beautify"),
            v("Emigrar", "To emigrate"), v("Empacotar", "To pack"),
            v("Empalidecer", "To turn pale"), v("Empreender", "To undertake"),
            v("Encaixar", "To fit in"), v("Encaminhar", "To forward"),
            v("Encarar", "To face"), v("Encarregar", "To put in charge"),
            v("Encobrir", "To cover up"), v("Endossar", "To endorse"),
            v("Enfatizar", "To emphasize"), v("Enfraquecer", "To weaken"),
            v("Engajar", "To engage"), v("Engordar", "To fatten"),
            v("Enigmatizar", "To enigmatize"), v("Ensacar", "To bag"),
            v("Entrar", "To enter"), v("Entreter", "To entertain", true),
            v("Entristecer", "To sadden"), v("Enumerar", "To enumerate"),
            v("Envelhecer", "To age"), v("Envenenar", "To poison"),
            v("Enxergar", "To see/perceive"), v("Equilibrar", "To balance"),
            v("Equipar", "To equip"), v("Equivaler", "To be equivalent"),
            v("Escalar", "To climb"), v("Escandalizar", "To scandalize"),
            v("Escapar", "To escape"), v("Esclarecer", "To clarify"),
            v("Escoltar", "To escort"), v("Especializar", "To specialize"),
            v("Especificar", "To specify"), v("Especular", "To speculate"),
            v("Espelhar", "To mirror"), v("Espalhar", "To spread"),
            v("Esquentar", "To heat"), v("Estabilizar", "To stabilize"),
            v("Estacionar", "To park"), v("Estalear", "To crack"),
            v("Estipular", "To stipulate"), v("Estocar", "To stock"),
            v("Estourar", "To burst"), v("Esvaziar", "To empty"),
        ]
    }
}
