import Foundation

extension VerbGlossaryService {
    static func glossaryAtoB() -> [GlossaryVerb] {
        [
            v("Abalar", "To shake"), v("Abandonar", "To abandon"), v("Abaixar", "To lower"),
            v("Abastecer", "To supply"), v("Abençoar", "To bless"), v("Abolir", "To abolish"),
            v("Abordar", "To approach"), v("Aborrecer", "To annoy"), v("Abraçar", "To hug"),
            v("Abrandar", "To soften"), v("Abreviar", "To abbreviate"), v("Abrigar", "To shelter"),
            v("Abrir", "To open"), v("Absorver", "To absorb"), v("Abusar", "To abuse"),
            v("Acabar", "To finish"), v("Acalmar", "To calm"), v("Acariciar", "To caress"),
            v("Aceitar", "To accept"), v("Acender", "To light/turn on"), v("Acessar", "To access"),
            v("Achar", "To find/think"), v("Aclarar", "To clarify"), v("Acolher", "To welcome"),
            v("Acompanhar", "To accompany"), v("Aconselhar", "To advise"), v("Acontecer", "To happen"),
            v("Acordar", "To wake up"), v("Acostumar", "To get used to"), v("Acreditar", "To believe"),
            v("Acrescentar", "To add"), v("Acudir", "To rush to help"), v("Acumular", "To accumulate"),
            v("Acusar", "To accuse"), v("Adaptar", "To adapt"), v("Adicionar", "To add"),
            v("Adivinhar", "To guess"), v("Admirar", "To admire"), v("Adoçar", "To sweeten"),
            v("Adoecer", "To fall ill"), v("Adorar", "To adore"), v("Adormecer", "To fall asleep"),
            v("Adquirir", "To acquire", true), v("Advertir", "To warn", true), v("Afastar", "To move away"),
            v("Afetar", "To affect"), v("Afirmar", "To affirm"), v("Afrouxar", "To loosen"),
            v("Agarrar", "To grab"), v("Agir", "To act", true), v("Agitar", "To shake/agitate"),
            v("Agradar", "To please"), v("Agradecer", "To thank"), v("Agregar", "To aggregate"),
            v("Aguardar", "To await"), v("Aguentar", "To endure"), v("Ajudar", "To help"),
            v("Ajustar", "To adjust"), v("Alcançar", "To reach"), v("Alegrar", "To cheer up"),
            v("Alertar", "To alert"), v("Alimentar", "To feed"), v("Aliviar", "To relieve"),
            v("Almoçar", "To have lunch"), v("Alterar", "To alter"), v("Alugar", "To rent"),
            v("Amar", "To love"), v("Ameaçar", "To threaten"), v("Amolecer", "To soften"),
            v("Ampliar", "To expand"), v("Analisar", "To analyze"), v("Andar", "To walk"),
            v("Animar", "To animate/cheer"), v("Anotar", "To note down"), v("Antecipar", "To anticipate"),
            v("Anunciar", "To announce"), v("Apagar", "To erase/turn off"), v("Apanhar", "To catch"),
            v("Aparecer", "To appear"), v("Aparentar", "To appear/seem"), v("Apegar", "To attach"),
            v("Apertar", "To tighten"), v("Apontar", "To point"), v("Apostar", "To bet"),
            v("Apreciar", "To appreciate"), v("Aprender", "To learn"), v("Apresentar", "To present"),
            v("Apressar", "To hurry"), v("Aprovar", "To approve"), v("Aproximar", "To approach"),
            v("Arrancar", "To pull out"), v("Arranjar", "To arrange"), v("Arrastar", "To drag"),
            v("Arrecadar", "To collect"), v("Arriscar", "To risk"), v("Arrumar", "To tidy up"),
            v("Aspirar", "To aspire"), v("Assegurar", "To assure"), v("Assinalar", "To mark"),
            v("Assinar", "To sign"), v("Assistir", "To watch/attend"), v("Associar", "To associate"),
            v("Assumir", "To assume"), v("Assustar", "To scare"), v("Atacar", "To attack"),
            v("Atar", "To tie"), v("Atender", "To answer/serve"), v("Atingir", "To reach/hit"),
            v("Atirar", "To throw/shoot"), v("Atraer", "To attract"), v("Atrapalhar", "To confuse/hinder"),
            v("Atrasar", "To delay"), v("Atrair", "To attract", true), v("Atravessar", "To cross"),
            v("Atrever", "To dare"), v("Atribuir", "To attribute"), v("Atuar", "To act/perform"),
            v("Aumentar", "To increase"), v("Autorizar", "To authorize"), v("Avaliar", "To evaluate"),
            v("Avançar", "To advance"), v("Avisar", "To warn/notify"),
            v("Baixar", "To lower/download"), v("Banhar", "To bathe"), v("Bastar", "To suffice"),
            v("Bater", "To hit/knock"), v("Batizar", "To baptize"), v("Beber", "To drink"),
            v("Beijar", "To kiss"), v("Beneficiar", "To benefit"), v("Bloquear", "To block"),
            v("Bordar", "To embroider"), v("Brilhar", "To shine"), v("Brincar", "To play (fun)"),
            v("Brigar", "To fight/argue"), v("Buscar", "To search/fetch"),
        ]
    }
}
