import Foundation

extension VerbGlossaryService {
    static func glossaryEtoI() -> [GlossaryVerb] {
        [
            v("Economizar", "To save (money)"), v("Editar", "To edit"),
            v("Educar", "To educate"), v("Efetuar", "To carry out"),
            v("Elaborar", "To elaborate"), v("Eleger", "To elect"),
            v("Eliminar", "To eliminate"), v("Embarcar", "To board"),
            v("Emitir", "To emit/issue"), v("Emocionar", "To move (emotionally)"),
            v("Empenhar", "To commit/pledge"), v("Empregar", "To employ"),
            v("Empurrar", "To push"), v("Encantar", "To enchant"),
            v("Encerrar", "To close/end"), v("Encher", "To fill"),
            v("Encolher", "To shrink"), v("Encontrar", "To find/meet"),
            v("Encorajar", "To encourage"), v("Endireitar", "To straighten"),
            v("Enfrentar", "To face"), v("Enganar", "To deceive"),
            v("Engolir", "To swallow"), v("Enlouquecer", "To drive crazy"),
            v("Enriquecer", "To enrich"), v("Ensaiar", "To rehearse"),
            v("Ensinar", "To teach"), v("Entender", "To understand"),
            v("Enterrar", "To bury"), v("Entregar", "To deliver"),
            v("Entrevistar", "To interview"), v("Enviar", "To send"),
            v("Envolver", "To involve"), v("Erguer", "To raise"),
            v("Errar", "To err/make a mistake"), v("Escolher", "To choose"),
            v("Esconder", "To hide"), v("Escrever", "To write"),
            v("Escutar", "To listen"), v("Esforçar", "To make an effort"),
            v("Esgotar", "To exhaust"), v("Espantar", "To scare"),
            v("Esperar", "To wait/hope"), v("Esquecer", "To forget"),
            v("Estabelecer", "To establish"), v("Estar", "To be (temporary)", true),
            v("Estimar", "To estimate/esteem"), v("Estimular", "To stimulate"),
            v("Esticar", "To stretch"), v("Estranhar", "To find strange"),
            v("Estrear", "To premiere"), v("Estudar", "To study"),
            v("Evitar", "To avoid"), v("Evocar", "To evoke"),
            v("Exagerar", "To exaggerate"), v("Examinar", "To examine"),
            v("Excluir", "To exclude"), v("Executar", "To execute"),
            v("Exercer", "To exercise/practice"), v("Exercitar", "To exercise"),
            v("Exibir", "To exhibit"), v("Exigir", "To demand"),
            v("Existir", "To exist"), v("Expandir", "To expand"),
            v("Experimentar", "To try/experiment"), v("Explicar", "To explain"),
            v("Explorar", "To explore"), v("Exportar", "To export"),
            v("Expressar", "To express"), v("Expulsar", "To expel"),
            v("Fabricar", "To manufacture"), v("Facilitar", "To facilitate"),
            v("Falar", "To speak"), v("Falhar", "To fail"),
            v("Faltar", "To lack/miss"), v("Familiarizar", "To familiarize"),
            v("Fantasiar", "To fantasize"), v("Fartar", "To fill up"),
            v("Favorecer", "To favor"), v("Fazer", "To do/make", true),
            v("Fechar", "To close"), v("Ferir", "To wound", true),
            v("Festejar", "To celebrate"), v("Ficar", "To stay/remain"),
            v("Filmar", "To film"), v("Filtrar", "To filter"),
            v("Financiar", "To finance"), v("Fingir", "To pretend"),
            v("Fixar", "To fix/attach"), v("Florescer", "To flourish"),
            v("Fluir", "To flow"), v("Focar", "To focus"),
            v("Forçar", "To force"), v("Formar", "To form/graduate"),
            v("Fornecer", "To supply"), v("Fortalecer", "To strengthen"),
            v("Fotografar", "To photograph"), v("Frequentar", "To frequent"),
            v("Fritar", "To fry"), v("Frustrar", "To frustrate"),
            v("Fugir", "To flee", true), v("Fumar", "To smoke"),
            v("Funcionar", "To work/function"), v("Fundar", "To found"),
            v("Gastar", "To spend"), v("Gerar", "To generate"),
            v("Gerenciar", "To manage"), v("Glorificar", "To glorify"),
            v("Gostar", "To like"), v("Governar", "To govern"),
            v("Gravar", "To record"), v("Gritar", "To shout"),
            v("Guardar", "To keep/store"), v("Guiar", "To guide"),
            v("Habituar", "To get used to"), v("Harmonizar", "To harmonize"),
            v("Haver", "To exist/there is", true), v("Herdar", "To inherit"),
            v("Hesitar", "To hesitate"), v("Honrar", "To honor"),
            v("Hospedar", "To host"),
            v("Identificar", "To identify"), v("Ignorar", "To ignore"),
            v("Iluminar", "To illuminate"), v("Ilustrar", "To illustrate"),
            v("Imaginar", "To imagine"), v("Imitar", "To imitate"),
            v("Impedir", "To prevent", true), v("Implementar", "To implement"),
            v("Implicar", "To imply"), v("Importar", "To import/matter"),
            v("Impor", "To impose", true), v("Impressionar", "To impress"),
            v("Imprimir", "To print"), v("Inaugurar", "To inaugurate"),
            v("Incluir", "To include"), v("Incomodar", "To bother"),
            v("Incorporar", "To incorporate"), v("Indicar", "To indicate"),
            v("Influenciar", "To influence"), v("Informar", "To inform"),
            v("Iniciar", "To initiate"), v("Inscrever", "To register/enroll"),
            v("Inserir", "To insert"), v("Insistir", "To insist"),
            v("Inspirar", "To inspire"), v("Instalar", "To install"),
            v("Instruir", "To instruct"), v("Integrar", "To integrate"),
            v("Interessar", "To interest"), v("Interpretar", "To interpret"),
            v("Interrogar", "To interrogate"), v("Interromper", "To interrupt"),
            v("Introduzir", "To introduce", true), v("Invadir", "To invade"),
            v("Inventar", "To invent"), v("Investigar", "To investigate"),
            v("Investir", "To invest"), v("Ir", "To go", true),
            v("Irritar", "To irritate"), v("Isolar", "To isolate"),
        ]
    }
}
