import Foundation

extension VerbGlossaryService {
    static func glossaryJtoR() -> [GlossaryVerb] {
        [
            v("Jantar", "To have dinner"), v("Jogar", "To play (games)"),
            v("Julgar", "To judge"), v("Juntar", "To join/gather"),
            v("Jurar", "To swear"), v("Justificar", "To justify"),
            v("Lamentar", "To regret"), v("Lançar", "To launch"),
            v("Largar", "To let go"), v("Lavar", "To wash"),
            v("Legitimar", "To legitimize"), v("Ler", "To read", true),
            v("Levantar", "To raise/get up"), v("Levar", "To take/carry"),
            v("Libertar", "To free"), v("Lidar", "To deal with"),
            v("Ligar", "To call/turn on"), v("Limitar", "To limit"),
            v("Limpar", "To clean"), v("Localizar", "To locate"),
            v("Lutar", "To fight"), v("Machucar", "To hurt"),
            v("Manter", "To maintain", true), v("Marcar", "To mark/schedule"),
            v("Mastigar", "To chew"), v("Matar", "To kill"),
            v("Medir", "To measure", true), v("Melhorar", "To improve"),
            v("Mencionar", "To mention"), v("Mentir", "To lie", true),
            v("Merecer", "To deserve"), v("Mergulhar", "To dive"),
            v("Misturar", "To mix"), v("Mobilizar", "To mobilize"),
            v("Modificar", "To modify"), v("Moer", "To grind", true),
            v("Molhar", "To wet"), v("Montar", "To assemble/ride"),
            v("Morar", "To live/reside"), v("Morder", "To bite"),
            v("Morrer", "To die"), v("Mostrar", "To show"),
            v("Motivar", "To motivate"), v("Mover", "To move"),
            v("Mudar", "To change/move"), v("Multiplicar", "To multiply"),
            v("Nadar", "To swim"), v("Namorar", "To date"),
            v("Narrar", "To narrate"), v("Nascer", "To be born"),
            v("Necessitar", "To need"), v("Negar", "To deny"),
            v("Negociar", "To negotiate"), v("Nomear", "To name/appoint"),
            v("Notar", "To notice"), v("Nutrir", "To nourish"),
            v("Obedecer", "To obey"), v("Obrigar", "To oblige"),
            v("Observar", "To observe"), v("Obter", "To obtain", true),
            v("Ocupar", "To occupy"), v("Ofender", "To offend"),
            v("Oferecer", "To offer"), v("Olhar", "To look"),
            v("Operar", "To operate"), v("Opor", "To oppose", true),
            v("Optar", "To opt"), v("Orar", "To pray"),
            v("Ordenar", "To order"), v("Organizar", "To organize"),
            v("Orientar", "To guide/orient"), v("Originar", "To originate"),
            v("Ousar", "To dare"), v("Ouvir", "To hear/listen", true),
            v("Pagar", "To pay"), v("Parar", "To stop"),
            v("Parecer", "To seem/appear"), v("Participar", "To participate"),
            v("Partir", "To leave/depart"), v("Passar", "To pass"),
            v("Passear", "To stroll"), v("Patrocinar", "To sponsor"),
            v("Pedir", "To ask for", true), v("Pegar", "To catch/grab"),
            v("Pendurar", "To hang"), v("Pensar", "To think"),
            v("Perceber", "To perceive/realize"), v("Perder", "To lose", true),
            v("Perdoar", "To forgive"), v("Permitir", "To allow"),
            v("Perseguir", "To pursue"), v("Pertencer", "To belong"),
            v("Perturbar", "To disturb"), v("Pesar", "To weigh"),
            v("Pesquisar", "To research"), v("Pintar", "To paint"),
            v("Pisar", "To step on"), v("Planejar", "To plan"),
            v("Plantar", "To plant"), v("Poder", "To be able/can", true),
            v("Polir", "To polish", true), v("Poluir", "To pollute"),
            v("Pôr", "To put/place", true), v("Portar", "To carry/behave"),
            v("Posicionar", "To position"), v("Possibilitar", "To make possible"),
            v("Possuir", "To possess"), v("Postar", "To post"),
            v("Poupar", "To save"), v("Praticar", "To practice"),
            v("Precisar", "To need"), v("Preferir", "To prefer", true),
            v("Prejudicar", "To harm"), v("Premiar", "To award"),
            v("Prender", "To arrest/fasten"), v("Preocupar", "To worry"),
            v("Preparar", "To prepare"), v("Presenciar", "To witness"),
            v("Preservar", "To preserve"), v("Pressionar", "To pressure"),
            v("Pretender", "To intend"), v("Prevenir", "To prevent"),
            v("Prever", "To foresee", true), v("Privar", "To deprive"),
            v("Processar", "To process/sue"), v("Procurar", "To look for"),
            v("Produzir", "To produce", true), v("Progredir", "To progress"),
            v("Proibir", "To prohibit"), v("Prolongar", "To prolong"),
            v("Prometer", "To promise"), v("Promover", "To promote"),
            v("Pronunciar", "To pronounce"), v("Propor", "To propose", true),
            v("Proporcionar", "To provide"), v("Proteger", "To protect"),
            v("Protestar", "To protest"), v("Provar", "To prove/taste"),
            v("Provocar", "To provoke"), v("Publicar", "To publish"),
            v("Punir", "To punish"), v("Puxar", "To pull"),
            v("Qualificar", "To qualify"), v("Quebrar", "To break"),
            v("Queimar", "To burn"), v("Queixar", "To complain"),
            v("Querer", "To want", true), v("Questionar", "To question"),
            v("Reagir", "To react"), v("Realizar", "To accomplish"),
            v("Receber", "To receive"), v("Reclamar", "To complain"),
            v("Recomendar", "To recommend"), v("Reconhecer", "To recognize"),
            v("Recordar", "To remember"), v("Recorrer", "To resort to"),
            v("Recuperar", "To recover"), v("Recusar", "To refuse"),
            v("Reduzir", "To reduce", true), v("Referir", "To refer"),
            v("Refletir", "To reflect"), v("Reformar", "To reform"),
            v("Regar", "To water"), v("Registrar", "To register"),
            v("Regressar", "To return"), v("Regular", "To regulate"),
            v("Rejeitar", "To reject"), v("Relacionar", "To relate"),
            v("Relaxar", "To relax"), v("Relembrar", "To recall"),
            v("Relatar", "To report"), v("Renovar", "To renew"),
            v("Renunciar", "To renounce"), v("Reparar", "To repair/notice"),
            v("Repetir", "To repeat", true), v("Representar", "To represent"),
            v("Reproduzir", "To reproduce", true), v("Requerer", "To require"),
            v("Reservar", "To reserve"), v("Residir", "To reside"),
            v("Resistir", "To resist"), v("Resolver", "To solve"),
            v("Respeitar", "To respect"), v("Respirar", "To breathe"),
            v("Responder", "To answer"), v("Ressaltar", "To highlight"),
            v("Restaurar", "To restore"), v("Resultar", "To result"),
            v("Resumir", "To summarize"), v("Retirar", "To remove"),
            v("Retornar", "To return"), v("Reunir", "To gather"),
            v("Revelar", "To reveal"), v("Rever", "To review"),
            v("Rezar", "To pray"), v("Rir", "To laugh", true),
            v("Roubar", "To steal"), v("Rodar", "To rotate"),
            v("Romper", "To break"),
        ]
    }
}
