import Foundation

extension VerbGlossaryService {
    static func glossaryStoZ() -> [GlossaryVerb] {
        [
            v("Saber", "To know (facts)", true),
            v("Sacudir", "To shake"), v("Sair", "To leave/go out", true),
            v("Saltar", "To jump"), v("Salvar", "To save"),
            v("Satisfazer", "To satisfy", true), v("Secar", "To dry"),
            v("Seguir", "To follow", true), v("Segurar", "To hold"),
            v("Selecionar", "To select"), v("Sentar", "To sit"),
            v("Sentir", "To feel", true), v("Separar", "To separate"),
            v("Ser", "To be (permanent)", true), v("Servir", "To serve", true),
            v("Significar", "To mean"), v("Silenciar", "To silence"),
            v("Simbolizar", "To symbolize"), v("Simplificar", "To simplify"),
            v("Simular", "To simulate"), v("Situar", "To situate"),
            v("Sobrar", "To be left over"), v("Sobreviver", "To survive"),
            v("Sofrer", "To suffer"), v("Soltar", "To release"),
            v("Solucionar", "To solve"), v("Sonhar", "To dream"),
            v("Sorrir", "To smile", true), v("Subir", "To go up"),
            v("Substituir", "To substitute"), v("Suceder", "To succeed/happen"),
            v("Sugerir", "To suggest", true), v("Sumir", "To disappear"),
            v("Superar", "To overcome"), v("Supor", "To suppose", true),
            v("Suportar", "To support/endure"), v("Surgir", "To arise"),
            v("Surpreender", "To surprise"), v("Suspeitar", "To suspect"),
            v("Suspender", "To suspend"), v("Sustentar", "To sustain"),
            v("Tapar", "To cover"), v("Tecer", "To weave"),
            v("Telefonar", "To telephone"), v("Temer", "To fear"),
            v("Tentar", "To try"), v("Ter", "To have", true),
            v("Terminar", "To finish"), v("Testemunhar", "To testify"),
            v("Tirar", "To take out/remove"), v("Tocar", "To touch/play music"),
            v("Tolerar", "To tolerate"), v("Tomar", "To take/have"),
            v("Torcer", "To twist/root for"), v("Tornar", "To become/make"),
            v("Trabalhar", "To work"), v("Traduzir", "To translate", true),
            v("Trair", "To betray", true), v("Trancar", "To lock"),
            v("Transferir", "To transfer"), v("Transformar", "To transform"),
            v("Transmitir", "To transmit"), v("Transportar", "To transport"),
            v("Tratar", "To treat"), v("Trazer", "To bring", true),
            v("Treinar", "To train"), v("Trocar", "To exchange"),
            v("Unir", "To unite"), v("Usar", "To use"),
            v("Utilizar", "To utilize"), v("Valer", "To be worth", true),
            v("Valorizar", "To value"), v("Variar", "To vary"),
            v("Varrer", "To sweep"), v("Vencer", "To win/overcome"),
            v("Vender", "To sell"), v("Ver", "To see", true),
            v("Verificar", "To verify"), v("Vestir", "To dress", true),
            v("Viajar", "To travel"), v("Vigiar", "To watch over"),
            v("Vincular", "To link"), v("Vir", "To come", true),
            v("Virar", "To turn"), v("Visitar", "To visit"),
            v("Visualizar", "To visualize"), v("Viver", "To live"),
            v("Voar", "To fly"), v("Voltar", "To return"),
            v("Votar", "To vote"), v("Xingar", "To curse/swear at"),
            v("Zelar", "To watch over/care for"),
        ]
    }
}
