import Foundation

extension VerbGlossaryService {
    static func glossaryCtoD() -> [GlossaryVerb] {
        [
            v("Caber", "To fit", true), v("Caçar", "To hunt"), v("Cair", "To fall", true),
            v("Calar", "To silence"), v("Calcular", "To calculate"), v("Calçar", "To put on shoes"),
            v("Caminhar", "To walk/hike"), v("Cancelar", "To cancel"), v("Cansar", "To tire"),
            v("Cantar", "To sing"), v("Capturar", "To capture"), v("Caracterizar", "To characterize"),
            v("Carecer", "To lack"), v("Carregar", "To carry/charge"), v("Casar", "To marry"),
            v("Causar", "To cause"), v("Ceder", "To yield"), v("Celebrar", "To celebrate"),
            v("Censurar", "To censor"), v("Cercar", "To surround"), v("Certificar", "To certify"),
            v("Chamar", "To call"), v("Chatear", "To annoy"), v("Chegar", "To arrive"),
            v("Cheirar", "To smell"), v("Chorar", "To cry"), v("Chutar", "To kick"),
            v("Circular", "To circulate"), v("Citar", "To cite"), v("Classificar", "To classify"),
            v("Cobrar", "To charge/collect"), v("Cobrir", "To cover", true), v("Colar", "To glue"),
            v("Colocar", "To place"), v("Colorir", "To color"), v("Combater", "To combat"),
            v("Combinar", "To combine/agree"), v("Começar", "To begin"), v("Comentar", "To comment"),
            v("Comer", "To eat"), v("Comparar", "To compare"), v("Comparecer", "To appear/attend"),
            v("Compartilhar", "To share"), v("Compensar", "To compensate"), v("Competir", "To compete", true),
            v("Complementar", "To complement"), v("Completar", "To complete"),
            v("Complicar", "To complicate"), v("Compor", "To compose", true),
            v("Comportar", "To behave"), v("Comprar", "To buy"), v("Compreender", "To understand"),
            v("Comprometer", "To commit"), v("Comunicar", "To communicate"),
            v("Concentrar", "To concentrate"), v("Concluir", "To conclude"),
            v("Concordar", "To agree"), v("Condenar", "To condemn"),
            v("Conduzir", "To drive/lead", true), v("Conectar", "To connect"),
            v("Confessar", "To confess"), v("Confiar", "To trust"),
            v("Confirmar", "To confirm"), v("Confundir", "To confuse"),
            v("Conhecer", "To know (people)"), v("Conjugar", "To conjugate"),
            v("Conquistar", "To conquer"), v("Conseguir", "To manage/achieve", true),
            v("Consentir", "To consent", true), v("Conservar", "To conserve"),
            v("Considerar", "To consider"), v("Consistir", "To consist"),
            v("Consolar", "To console"), v("Constituir", "To constitute"),
            v("Construir", "To build"), v("Consultar", "To consult"),
            v("Consumir", "To consume"), v("Contar", "To count/tell"),
            v("Contemplar", "To contemplate"), v("Conter", "To contain", true),
            v("Contestar", "To contest"), v("Continuar", "To continue"),
            v("Contradizer", "To contradict", true), v("Contratar", "To hire"),
            v("Contribuir", "To contribute"), v("Controlar", "To control"),
            v("Convencer", "To convince"), v("Conversar", "To converse"),
            v("Converter", "To convert"), v("Convidar", "To invite"),
            v("Conviver", "To live with"), v("Cooperar", "To cooperate"),
            v("Copiar", "To copy"), v("Corrigir", "To correct", true),
            v("Correr", "To run"), v("Corresponder", "To correspond"),
            v("Cortar", "To cut"), v("Costurar", "To sew"),
            v("Cozinhar", "To cook"), v("Crescer", "To grow"),
            v("Criar", "To create"), v("Criticar", "To criticize"),
            v("Cruzar", "To cross"), v("Cuidar", "To take care"),
            v("Culpar", "To blame"), v("Cultivar", "To cultivate"),
            v("Cumprir", "To fulfill"), v("Curar", "To cure"),
            v("Cursar", "To study/take a course"), v("Custar", "To cost"),
            v("Danificar", "To damage"), v("Dançar", "To dance"),
            v("Dar", "To give", true), v("Debater", "To debate"),
            v("Decidir", "To decide"), v("Declarar", "To declare"),
            v("Decorar", "To decorate/memorize"), v("Dedicar", "To dedicate"),
            v("Defender", "To defend"), v("Definir", "To define"),
            v("Deixar", "To leave/let"), v("Demorar", "To take long"),
            v("Demonstrar", "To demonstrate"), v("Denunciar", "To denounce"),
            v("Depender", "To depend"), v("Depositar", "To deposit"),
            v("Derramar", "To spill"), v("Derrotar", "To defeat"),
            v("Desafiar", "To challenge"), v("Desanimar", "To discourage"),
            v("Desaparecer", "To disappear"), v("Descansar", "To rest"),
            v("Descer", "To go down"), v("Descobrir", "To discover", true),
            v("Desconfiar", "To suspect"), v("Descrever", "To describe"),
            v("Desculpar", "To excuse"), v("Desejar", "To wish/desire"),
            v("Desempenhar", "To perform"), v("Desenhar", "To draw"),
            v("Desenvolver", "To develop"), v("Desistir", "To give up"),
            v("Desligar", "To turn off"), v("Deslocar", "To displace"),
            v("Despedir", "To fire/say goodbye", true), v("Despertar", "To awaken"),
            v("Destacar", "To highlight"), v("Destinar", "To destine"),
            v("Destruir", "To destroy"), v("Desviar", "To deviate"),
            v("Detestar", "To detest"), v("Dever", "To must/owe"),
            v("Devolver", "To return (something)"), v("Dizer", "To say/tell", true),
            v("Doar", "To donate"), v("Doer", "To hurt", true),
            v("Dominar", "To dominate"), v("Dormir", "To sleep", true),
            v("Duvidar", "To doubt"),
        ]
    }
}
