import Foundation

@Observable
@MainActor
class VerbGlossaryService {
    private(set) var allVerbs: [GlossaryVerb] = []
    private(set) var isLoaded: Bool = false

    init() {
        loadVerbs()
    }

    func loadVerbs() {
        allVerbs = Self.buildGlossary()
        isLoaded = true
    }

    func search(_ query: String) -> [GlossaryVerb] {
        guard !query.isEmpty else { return allVerbs }
        return allVerbs.filter {
            $0.infinitive.localizedStandardContains(query) ||
            $0.translation.localizedStandardContains(query)
        }
    }

    var verbCount: Int { allVerbs.count }

    private static func v(_ inf: String, _ trans: String, _ irr: Bool = false) -> GlossaryVerb {
        GlossaryVerb(infinitive: inf, translation: trans, irregular: irr)
    }

    private static func buildGlossary() -> [GlossaryVerb] {
        [
            v("Abalar", "To shake"), v("Abandonar", "To abandon"), v("Abaixar", "To lower"),
            v("Abastecer", "To supply"), v("Abençoar", "To bless"), v("Abolir", "To abolish"),
            v("Abordar", "To approach"), v("Aborrecer", "To annoy"), v("Abraçar", "To hug"),
            v("Abrandar", "To soften"), v("Abreviar", "To abbreviate"), v("Abrigar", "To shelter"),
            v("Abrir", "To open"), v("Absorver", "To absorb"), v("Abusar", "To abuse"),
            v("Acabar", "To finish"), v("Acalmar", "To calm"), v("Acariciar", "To caress"),
            v("Aceitar", "To accept"), v("Acender", "To light/turn on"), v("Acessar", "To access"),
            v("Achar", "To find/think"), v("Aclarar", "To clarify"), v("Acolher", "To welcome"),
            v("Acompanhar", "To accompany"), v("Aconselhar", "To advise"), v("Acontecer", "To happen"),
            v("Acordar", "To wake up"), v("Acostumar", "To get used to"), v("Acreditar", "To believe"),
            v("Acrescentar", "To add"), v("Acudir", "To rush to help"), v("Acumular", "To accumulate"),
            v("Acusar", "To accuse"), v("Adaptar", "To adapt"), v("Adicionar", "To add"),
            v("Adivinhar", "To guess"), v("Admirar", "To admire"), v("Adoçar", "To sweeten"),
            v("Adoecer", "To fall ill"), v("Adorar", "To adore"), v("Adormecer", "To fall asleep"),
            v("Adquirir", "To acquire", true), v("Advertir", "To warn", true), v("Afastar", "To move away"),
            v("Afetar", "To affect"), v("Afirmar", "To affirm"), v("Afrouxar", "To loosen"),
            v("Agarrar", "To grab"), v("Agir", "To act", true), v("Agitar", "To shake/agitate"),
            v("Agradar", "To please"), v("Agradecer", "To thank"), v("Agregar", "To aggregate"),
            v("Aguardar", "To await"), v("Aguentar", "To endure"), v("Ajudar", "To help"),
            v("Ajustar", "To adjust"), v("Alcançar", "To reach"), v("Alegrar", "To cheer up"),
            v("Alertar", "To alert"), v("Alimentar", "To feed"), v("Aliviar", "To relieve"),
            v("Almoçar", "To have lunch"), v("Alterar", "To alter"), v("Alugar", "To rent"),
            v("Amar", "To love"), v("Ameaçar", "To threaten"), v("Amolecer", "To soften"),
            v("Ampliar", "To expand"), v("Analisar", "To analyze"), v("Andar", "To walk"),
            v("Animar", "To animate/cheer"), v("Anotar", "To note down"), v("Antecipar", "To anticipate"),
            v("Anunciar", "To announce"), v("Apagar", "To erase/turn off"), v("Apanhar", "To catch"),
            v("Aparecer", "To appear"), v("Aparentar", "To appear/seem"), v("Apegar", "To attach"),
            v("Apertar", "To tighten"), v("Apontar", "To point"), v("Apostar", "To bet"),
            v("Apreciar", "To appreciate"), v("Aprender", "To learn"), v("Apresentar", "To present"),
            v("Apressar", "To hurry"), v("Aprovar", "To approve"), v("Aproximar", "To approach"),
            v("Arrancar", "To pull out"), v("Arranjar", "To arrange"), v("Arrastar", "To drag"),
            v("Arrecadar", "To collect"), v("Arriscar", "To risk"), v("Arrumar", "To tidy up"),
            v("Aspirar", "To aspire"), v("Assegurar", "To assure"), v("Assinalar", "To mark"),
            v("Assinar", "To sign"), v("Assistir", "To watch/attend"), v("Associar", "To associate"),
            v("Assumir", "To assume"), v("Assustar", "To scare"), v("Atacar", "To attack"),
            v("Atar", "To tie"), v("Atender", "To answer/serve"), v("Atingir", "To reach/hit"),
            v("Atirar", "To throw/shoot"), v("Atraer", "To attract"), v("Atrapalhar", "To confuse/hinder"),
            v("Atrasar", "To delay"), v("Atrair", "To attract", true), v("Atravessar", "To cross"),
            v("Atrever", "To dare"), v("Atribuir", "To attribute"), v("Atuar", "To act/perform"),
            v("Aumentar", "To increase"), v("Autorizar", "To authorize"), v("Avaliar", "To evaluate"),
            v("Avançar", "To advance"), v("Avisar", "To warn/notify"),
            v("Baixar", "To lower/download"), v("Banhar", "To bathe"), v("Bastar", "To suffice"),
            v("Bater", "To hit/knock"), v("Batizar", "To baptize"), v("Beber", "To drink"),
            v("Beijar", "To kiss"), v("Beneficiar", "To benefit"), v("Bloquear", "To block"),
            v("Bordar", "To embroider"), v("Brilhar", "To shine"), v("Brincar", "To play (fun)"),
            v("Brigar", "To fight/argue"), v("Buscar", "To search/fetch"),
            v("Caber", "To fit", true), v("Caçar", "To hunt"), v("Cair", "To fall", true),
            v("Calar", "To silence"), v("Calcular", "To calculate"), v("Calçar", "To put on shoes"),
            v("Caminhar", "To walk/hike"), v("Cancelar", "To cancel"), v("Cansar", "To tire"),
            v("Cantar", "To sing"), v("Capturar", "To capture"), v("Caracterizar", "To characterize"),
            v("Carecer", "To lack"), v("Carregar", "To carry/charge"), v("Casar", "To marry"),
            v("Causar", "To cause"), v("Ceder", "To yield"), v("Celebrar", "To celebrate"),
            v("Censurar", "To censor"), v("Cercar", "To surround"), v("Certificar", "To certify"),
            v("Chamar", "To call"), v("Chatear", "To annoy"), v("Chegar", "To arrive"),
            v("Cheirar", "To smell"), v("Chorar", "To cry"), v("Chutar", "To kick"),
            v("Circular", "To circulate"), v("Citar", "To cite"), v("Classificar", "To classify"),
            v("Cobrar", "To charge/collect"), v("Cobrir", "To cover", true), v("Colar", "To glue"),
            v("Colocar", "To place"), v("Colorir", "To color"), v("Combater", "To combat"),
            v("Combinar", "To combine/agree"), v("Começar", "To begin"), v("Comentar", "To comment"),
            v("Comer", "To eat"), v("Comparar", "To compare"), v("Comparecer", "To appear/attend"),
            v("Compartilhar", "To share"), v("Compensar", "To compensate"), v("Competir", "To compete", true),
            v("Complementar", "To complement"), v("Completar", "To complete"),
            v("Complicar", "To complicate"), v("Compor", "To compose", true),
            v("Comportar", "To behave"), v("Comprar", "To buy"), v("Compreender", "To understand"),
            v("Comprometer", "To commit"), v("Comunicar", "To communicate"),
            v("Concentrar", "To concentrate"), v("Concluir", "To conclude"),
            v("Concordar", "To agree"), v("Condenar", "To condemn"),
            v("Conduzir", "To drive/lead", true), v("Conectar", "To connect"),
            v("Confessar", "To confess"), v("Confiar", "To trust"),
            v("Confirmar", "To confirm"), v("Confundir", "To confuse"),
            v("Conhecer", "To know (people)"), v("Conjugar", "To conjugate"),
            v("Conquistar", "To conquer"), v("Conseguir", "To manage/achieve", true),
            v("Consentir", "To consent", true), v("Conservar", "To conserve"),
            v("Considerar", "To consider"), v("Consistir", "To consist"),
            v("Consolar", "To console"), v("Constituir", "To constitute"),
            v("Construir", "To build"), v("Consultar", "To consult"),
            v("Consumir", "To consume"), v("Contar", "To count/tell"),
            v("Contemplar", "To contemplate"), v("Conter", "To contain", true),
            v("Contestar", "To contest"), v("Continuar", "To continue"),
            v("Contradizer", "To contradict", true), v("Contratar", "To hire"),
            v("Contribuir", "To contribute"), v("Controlar", "To control"),
            v("Convencer", "To convince"), v("Conversar", "To converse"),
            v("Converter", "To convert"), v("Convidar", "To invite"),
            v("Conviver", "To live with"), v("Cooperar", "To cooperate"),
            v("Copiar", "To copy"), v("Corrigir", "To correct", true),
            v("Correr", "To run"), v("Corresponder", "To correspond"),
            v("Cortar", "To cut"), v("Costurar", "To sew"),
            v("Cozinhar", "To cook"), v("Crescer", "To grow"),
            v("Criar", "To create"), v("Criticar", "To criticize"),
            v("Cruzar", "To cross"), v("Cuidar", "To take care"),
            v("Culpar", "To blame"), v("Cultivar", "To cultivate"),
            v("Cumprir", "To fulfill"), v("Curar", "To cure"),
            v("Cursar", "To study/take a course"), v("Custar", "To cost"),
            v("Danificar", "To damage"), v("Dançar", "To dance"),
            v("Dar", "To give", true), v("Debater", "To debate"),
            v("Decidir", "To decide"), v("Declarar", "To declare"),
            v("Decorar", "To decorate/memorize"), v("Dedicar", "To dedicate"),
            v("Defender", "To defend"), v("Definir", "To define"),
            v("Deixar", "To leave/let"), v("Demorar", "To take long"),
            v("Demonstrar", "To demonstrate"), v("Denunciar", "To denounce"),
            v("Depender", "To depend"), v("Depositar", "To deposit"),
            v("Derramar", "To spill"), v("Derrotar", "To defeat"),
            v("Desafiar", "To challenge"), v("Desanimar", "To discourage"),
            v("Desaparecer", "To disappear"), v("Descansar", "To rest"),
            v("Descer", "To go down"), v("Descobrir", "To discover", true),
            v("Desconfiar", "To suspect"), v("Descrever", "To describe"),
            v("Desculpar", "To excuse"), v("Desejar", "To wish/desire"),
            v("Desempenhar", "To perform"), v("Desenhar", "To draw"),
            v("Desenvolver", "To develop"), v("Desistir", "To give up"),
            v("Desligar", "To turn off"), v("Deslocar", "To displace"),
            v("Despedir", "To fire/say goodbye", true), v("Despertar", "To awaken"),
            v("Destacar", "To highlight"), v("Destinar", "To destine"),
            v("Destruir", "To destroy"), v("Desviar", "To deviate"),
            v("Detestar", "To detest"), v("Dever", "To must/owe"),
            v("Devolver", "To return (something)"), v("Dizer", "To say/tell", true),
            v("Doar", "To donate"), v("Doer", "To hurt", true),
            v("Dominar", "To dominate"), v("Dormir", "To sleep", true),
            v("Duvidar", "To doubt"),
            v("Economizar", "To save (money)"), v("Editar", "To edit"),
            v("Educar", "To educate"), v("Efetuar", "To carry out"),
            v("Elaborar", "To elaborate"), v("Eleger", "To elect"),
            v("Eliminar", "To eliminate"), v("Embarcar", "To board"),
            v("Emitir", "To emit/issue"), v("Emocionar", "To move (emotionally)"),
            v("Empenhar", "To commit/pledge"), v("Empregar", "To employ"),
            v("Empurrar", "To push"), v("Encantar", "To enchant"),
            v("Encerrar", "To close/end"), v("Encher", "To fill"),
            v("Encolher", "To shrink"), v("Encontrar", "To find/meet"),
            v("Encorajar", "To encourage"), v("Endireitar", "To straighten"),
            v("Enfrentar", "To face"), v("Enganar", "To deceive"),
            v("Engolir", "To swallow"), v("Enlouquecer", "To drive crazy"),
            v("Enriquecer", "To enrich"), v("Ensaiar", "To rehearse"),
            v("Ensinar", "To teach"), v("Entender", "To understand"),
            v("Enterrar", "To bury"), v("Entregar", "To deliver"),
            v("Entrevistar", "To interview"), v("Enviar", "To send"),
            v("Envolver", "To involve"), v("Erguer", "To raise"),
            v("Errar", "To err/make a mistake"), v("Escolher", "To choose"),
            v("Esconder", "To hide"), v("Escrever", "To write"),
            v("Escutar", "To listen"), v("Esforçar", "To make an effort"),
            v("Esgotar", "To exhaust"), v("Espantar", "To scare"),
            v("Esperar", "To wait/hope"), v("Esquecer", "To forget"),
            v("Estabelecer", "To establish"), v("Estar", "To be (temporary)", true),
            v("Estimar", "To estimate/esteem"), v("Estimular", "To stimulate"),
            v("Esticar", "To stretch"), v("Estranhar", "To find strange"),
            v("Estrear", "To premiere"), v("Estudar", "To study"),
            v("Evitar", "To avoid"), v("Evocar", "To evoke"),
            v("Exagerar", "To exaggerate"), v("Examinar", "To examine"),
            v("Excluir", "To exclude"), v("Executar", "To execute"),
            v("Exercer", "To exercise/practice"), v("Exercitar", "To exercise"),
            v("Exibir", "To exhibit"), v("Exigir", "To demand"),
            v("Existir", "To exist"), v("Expandir", "To expand"),
            v("Experimentar", "To try/experiment"), v("Explicar", "To explain"),
            v("Explorar", "To explore"), v("Exportar", "To export"),
            v("Expressar", "To express"), v("Expulsar", "To expel"),
            v("Fabricar", "To manufacture"), v("Facilitar", "To facilitate"),
            v("Falar", "To speak"), v("Falhar", "To fail"),
            v("Faltar", "To lack/miss"), v("Familiarizar", "To familiarize"),
            v("Fantasiar", "To fantasize"), v("Fartar", "To fill up"),
            v("Favorecer", "To favor"), v("Fazer", "To do/make", true),
            v("Fechar", "To close"), v("Ferir", "To wound", true),
            v("Festejar", "To celebrate"), v("Ficar", "To stay/remain"),
            v("Filmar", "To film"), v("Filtrar", "To filter"),
            v("Financiar", "To finance"), v("Fingir", "To pretend"),
            v("Fixar", "To fix/attach"), v("Florescer", "To flourish"),
            v("Fluir", "To flow"), v("Focar", "To focus"),
            v("Forçar", "To force"), v("Formar", "To form/graduate"),
            v("Fornecer", "To supply"), v("Fortalecer", "To strengthen"),
            v("Fotografar", "To photograph"), v("Frequentar", "To frequent"),
            v("Fritar", "To fry"), v("Frustrar", "To frustrate"),
            v("Fugir", "To flee", true), v("Fumar", "To smoke"),
            v("Funcionar", "To work/function"), v("Fundar", "To found"),
            v("Gastar", "To spend"), v("Gerar", "To generate"),
            v("Gerenciar", "To manage"), v("Glorificar", "To glorify"),
            v("Gostar", "To like"), v("Governar", "To govern"),
            v("Gravar", "To record"), v("Gritar", "To shout"),
            v("Guardar", "To keep/store"), v("Guiar", "To guide"),
            v("Habituar", "To get used to"), v("Harmonizar", "To harmonize"),
            v("Haver", "To exist/there is", true), v("Herdar", "To inherit"),
            v("Hesitar", "To hesitate"), v("Honrar", "To honor"),
            v("Hospedar", "To host"),
            v("Identificar", "To identify"), v("Ignorar", "To ignore"),
            v("Iluminar", "To illuminate"), v("Ilustrar", "To illustrate"),
            v("Imaginar", "To imagine"), v("Imitar", "To imitate"),
            v("Impedir", "To prevent", true), v("Implementar", "To implement"),
            v("Implicar", "To imply"), v("Importar", "To import/matter"),
            v("Impor", "To impose", true), v("Impressionar", "To impress"),
            v("Imprimir", "To print"), v("Inaugurar", "To inaugurate"),
            v("Incluir", "To include"), v("Incomodar", "To bother"),
            v("Incorporar", "To incorporate"), v("Indicar", "To indicate"),
            v("Influenciar", "To influence"), v("Informar", "To inform"),
            v("Iniciar", "To initiate"), v("Inscrever", "To register/enroll"),
            v("Inserir", "To insert"), v("Insistir", "To insist"),
            v("Inspirar", "To inspire"), v("Instalar", "To install"),
            v("Instruir", "To instruct"), v("Integrar", "To integrate"),
            v("Interessar", "To interest"), v("Interpretar", "To interpret"),
            v("Interrogar", "To interrogate"), v("Interromper", "To interrupt"),
            v("Introduzir", "To introduce", true), v("Invadir", "To invade"),
            v("Inventar", "To invent"), v("Investigar", "To investigate"),
            v("Investir", "To invest"), v("Ir", "To go", true),
            v("Irritar", "To irritate"), v("Isolar", "To isolate"),
            v("Jantar", "To have dinner"), v("Jogar", "To play (games)"),
            v("Julgar", "To judge"), v("Juntar", "To join/gather"),
            v("Jurar", "To swear"), v("Justificar", "To justify"),
            v("Lamentar", "To regret"), v("Lançar", "To launch"),
            v("Largar", "To let go"), v("Lavar", "To wash"),
            v("Legitimar", "To legitimize"), v("Ler", "To read", true),
            v("Levantar", "To raise/get up"), v("Levar", "To take/carry"),
            v("Libertar", "To free"), v("Lidar", "To deal with"),
            v("Ligar", "To call/turn on"), v("Limitar", "To limit"),
            v("Limpar", "To clean"), v("Localizar", "To locate"),
            v("Lutar", "To fight"), v("Machucar", "To hurt"),
            v("Manter", "To maintain", true), v("Marcar", "To mark/schedule"),
            v("Mastigar", "To chew"), v("Matar", "To kill"),
            v("Medir", "To measure", true), v("Melhorar", "To improve"),
            v("Mencionar", "To mention"), v("Mentir", "To lie", true),
            v("Merecer", "To deserve"), v("Mergulhar", "To dive"),
            v("Misturar", "To mix"), v("Mobilizar", "To mobilize"),
            v("Modificar", "To modify"), v("Moer", "To grind", true),
            v("Molhar", "To wet"), v("Montar", "To assemble/ride"),
            v("Morar", "To live/reside"), v("Morder", "To bite"),
            v("Morrer", "To die"), v("Mostrar", "To show"),
            v("Motivar", "To motivate"), v("Mover", "To move"),
            v("Mudar", "To change/move"), v("Multiplicar", "To multiply"),
            v("Nadar", "To swim"), v("Namorar", "To date"),
            v("Narrar", "To narrate"), v("Nascer", "To be born"),
            v("Necessitar", "To need"), v("Negar", "To deny"),
            v("Negociar", "To negotiate"), v("Nomear", "To name/appoint"),
            v("Notar", "To notice"), v("Nutrir", "To nourish"),
            v("Obedecer", "To obey"), v("Obrigar", "To oblige"),
            v("Observar", "To observe"), v("Obter", "To obtain", true),
            v("Ocupar", "To occupy"), v("Ofender", "To offend"),
            v("Oferecer", "To offer"), v("Olhar", "To look"),
            v("Operar", "To operate"), v("Opor", "To oppose", true),
            v("Optar", "To opt"), v("Orar", "To pray"),
            v("Ordenar", "To order"), v("Organizar", "To organize"),
            v("Orientar", "To guide/orient"), v("Originar", "To originate"),
            v("Ousar", "To dare"), v("Ouvir", "To hear/listen", true),
            v("Pagar", "To pay"), v("Parar", "To stop"),
            v("Parecer", "To seem/appear"), v("Participar", "To participate"),
            v("Partir", "To leave/depart"), v("Passar", "To pass"),
            v("Passear", "To stroll"), v("Patrocinar", "To sponsor"),
            v("Pedir", "To ask for", true), v("Pegar", "To catch/grab"),
            v("Pendurar", "To hang"), v("Pensar", "To think"),
            v("Perceber", "To perceive/realize"), v("Perder", "To lose", true),
            v("Perdoar", "To forgive"), v("Permitir", "To allow"),
            v("Perseguir", "To pursue"), v("Pertencer", "To belong"),
            v("Perturbar", "To disturb"), v("Pesar", "To weigh"),
            v("Pesquisar", "To research"), v("Pintar", "To paint"),
            v("Pisar", "To step on"), v("Planejar", "To plan"),
            v("Plantar", "To plant"), v("Poder", "To be able/can", true),
            v("Polir", "To polish", true), v("Poluir", "To pollute"),
            v("Pôr", "To put/place", true), v("Portar", "To carry/behave"),
            v("Posicionar", "To position"), v("Possibilitar", "To make possible"),
            v("Possuir", "To possess"), v("Postar", "To post"),
            v("Poupar", "To save"), v("Praticar", "To practice"),
            v("Precisar", "To need"), v("Preferir", "To prefer", true),
            v("Prejudicar", "To harm"), v("Premiar", "To award"),
            v("Prender", "To arrest/fasten"), v("Preocupar", "To worry"),
            v("Preparar", "To prepare"), v("Presenciar", "To witness"),
            v("Preservar", "To preserve"), v("Pressionar", "To pressure"),
            v("Pretender", "To intend"), v("Prevenir", "To prevent"),
            v("Prever", "To foresee", true), v("Privar", "To deprive"),
            v("Processar", "To process/sue"), v("Procurar", "To look for"),
            v("Produzir", "To produce", true), v("Progredir", "To progress"),
            v("Proibir", "To prohibit"), v("Prolongar", "To prolong"),
            v("Prometer", "To promise"), v("Promover", "To promote"),
            v("Pronunciar", "To pronounce"), v("Propor", "To propose", true),
            v("Proporcionar", "To provide"), v("Proteger", "To protect"),
            v("Protestar", "To protest"), v("Provar", "To prove/taste"),
            v("Provocar", "To provoke"), v("Publicar", "To publish"),
            v("Punir", "To punish"), v("Puxar", "To pull"),
            v("Qualificar", "To qualify"), v("Quebrar", "To break"),
            v("Queimar", "To burn"), v("Queixar", "To complain"),
            v("Querer", "To want", true), v("Questionar", "To question"),
            v("Reagir", "To react"), v("Realizar", "To accomplish"),
            v("Receber", "To receive"), v("Reclamar", "To complain"),
            v("Recomendar", "To recommend"), v("Reconhecer", "To recognize"),
            v("Recordar", "To remember"), v("Recorrer", "To resort to"),
            v("Recuperar", "To recover"), v("Recusar", "To refuse"),
            v("Reduzir", "To reduce", true), v("Referir", "To refer"),
            v("Refletir", "To reflect"), v("Reformar", "To reform"),
            v("Regar", "To water"), v("Registrar", "To register"),
            v("Regressar", "To return"), v("Regular", "To regulate"),
            v("Rejeitar", "To reject"), v("Relacionar", "To relate"),
            v("Relaxar", "To relax"), v("Relembrar", "To recall"),
            v("Relatar", "To report"), v("Renovar", "To renew"),
            v("Renunciar", "To renounce"), v("Reparar", "To repair/notice"),
            v("Repetir", "To repeat", true), v("Representar", "To represent"),
            v("Reproduzir", "To reproduce", true), v("Requerer", "To require"),
            v("Reservar", "To reserve"), v("Residir", "To reside"),
            v("Resistir", "To resist"), v("Resolver", "To solve"),
            v("Respeitar", "To respect"), v("Respirar", "To breathe"),
            v("Responder", "To answer"), v("Ressaltar", "To highlight"),
            v("Restaurar", "To restore"), v("Resultar", "To result"),
            v("Resumir", "To summarize"), v("Retirar", "To remove"),
            v("Retornar", "To return"), v("Reunir", "To gather"),
            v("Revelar", "To reveal"), v("Rever", "To review"),
            v("Rezar", "To pray"), v("Rir", "To laugh", true),
            v("Roubar", "To steal"), v("Rodar", "To rotate"),
            v("Romper", "To break"), v("Saber", "To know (facts)", true),
            v("Sacudir", "To shake"), v("Sair", "To leave/go out", true),
            v("Saltar", "To jump"), v("Salvar", "To save"),
            v("Satisfazer", "To satisfy", true), v("Secar", "To dry"),
            v("Seguir", "To follow", true), v("Segurar", "To hold"),
            v("Selecionar", "To select"), v("Sentar", "To sit"),
            v("Sentir", "To feel", true), v("Separar", "To separate"),
            v("Ser", "To be (permanent)", true), v("Servir", "To serve", true),
            v("Significar", "To mean"), v("Silenciar", "To silence"),
            v("Simbolizar", "To symbolize"), v("Simplificar", "To simplify"),
            v("Simular", "To simulate"), v("Situar", "To situate"),
            v("Sobrar", "To be left over"), v("Sobreviver", "To survive"),
            v("Sofrer", "To suffer"), v("Soltar", "To release"),
            v("Solucionar", "To solve"), v("Sonhar", "To dream"),
            v("Sorrir", "To smile", true), v("Subir", "To go up"),
            v("Substituir", "To substitute"), v("Suceder", "To succeed/happen"),
            v("Sugerir", "To suggest", true), v("Sumir", "To disappear"),
            v("Superar", "To overcome"), v("Supor", "To suppose", true),
            v("Suportar", "To support/endure"), v("Surgir", "To arise"),
            v("Surpreender", "To surprise"), v("Suspeitar", "To suspect"),
            v("Suspender", "To suspend"), v("Sustentar", "To sustain"),
            v("Tapar", "To cover"), v("Tecer", "To weave"),
            v("Telefonar", "To telephone"), v("Temer", "To fear"),
            v("Tentar", "To try"), v("Ter", "To have", true),
            v("Terminar", "To finish"), v("Testemunhar", "To testify"),
            v("Tirar", "To take out/remove"), v("Tocar", "To touch/play music"),
            v("Tolerar", "To tolerate"), v("Tomar", "To take/have"),
            v("Torcer", "To twist/root for"), v("Tornar", "To become/make"),
            v("Trabalhar", "To work"), v("Traduzir", "To translate", true),
            v("Trair", "To betray", true), v("Trancar", "To lock"),
            v("Transferir", "To transfer"), v("Transformar", "To transform"),
            v("Transmitir", "To transmit"), v("Transportar", "To transport"),
            v("Tratar", "To treat"), v("Trazer", "To bring", true),
            v("Treinar", "To train"), v("Trocar", "To exchange"),
            v("Unir", "To unite"), v("Usar", "To use"),
            v("Utilizar", "To utilize"), v("Valer", "To be worth", true),
            v("Valorizar", "To value"), v("Variar", "To vary"),
            v("Varrer", "To sweep"), v("Vencer", "To win/overcome"),
            v("Vender", "To sell"), v("Ver", "To see", true),
            v("Verificar", "To verify"), v("Vestir", "To dress", true),
            v("Viajar", "To travel"), v("Vigiar", "To watch over"),
            v("Vincular", "To link"), v("Vir", "To come", true),
            v("Virar", "To turn"), v("Visitar", "To visit"),
            v("Visualizar", "To visualize"), v("Viver", "To live"),
            v("Voar", "To fly"), v("Voltar", "To return"),
            v("Votar", "To vote"), v("Xingar", "To curse/swear at"),
            v("Zelar", "To watch over/care for"),
            v("Abandonar-se", "To abandon oneself"), v("Acalmar-se", "To calm down"),
            v("Adaptar-se", "To adapt oneself"), v("Apaixonar-se", "To fall in love"),
            v("Arrepender-se", "To regret"), v("Atrever-se", "To dare"),
            v("Chamar-se", "To be called"), v("Comportar-se", "To behave"),
            v("Concentrar-se", "To concentrate"), v("Conformar-se", "To conform"),
            v("Deitar-se", "To lie down"), v("Dedicar-se", "To dedicate oneself"),
            v("Deparar-se", "To come across"), v("Despedir-se", "To say goodbye"),
            v("Divertir-se", "To have fun"), v("Entregar-se", "To surrender"),
            v("Esforçar-se", "To make an effort"), v("Expressar-se", "To express oneself"),
            v("Interessar-se", "To be interested"), v("Lavar-se", "To wash oneself"),
            v("Lembrar-se", "To remember"), v("Levantar-se", "To get up"),
            v("Mudar-se", "To move (house)"), v("Orgulhar-se", "To be proud"),
            v("Pentear-se", "To comb one's hair"), v("Preocupar-se", "To worry"),
            v("Preparar-se", "To prepare oneself"), v("Queixar-se", "To complain"),
            v("Referir-se", "To refer to"), v("Reunir-se", "To meet/gather"),
            v("Sentar-se", "To sit down"), v("Sentir-se", "To feel"),
            v("Vestir-se", "To get dressed"),
            v("Abanar", "To wave/fan"), v("Abdicar", "To abdicate"),
            v("Absorver", "To absorb"), v("Abstenir", "To abstain", true),
            v("Abusar", "To abuse"), v("Acalorar", "To heat up"),
            v("Acarretar", "To entail"), v("Acelerar", "To accelerate"),
            v("Acentuar", "To accentuate"), v("Adiar", "To postpone"),
            v("Administrar", "To administer"), v("Admitir", "To admit"),
            v("Adotar", "To adopt"), v("Adulterar", "To adulterate"),
            v("Afagar", "To caress"), v("Aferir", "To verify/gauge"),
            v("Afixar", "To affix"), v("Afogar", "To drown"),
            v("Aglomerar", "To agglomerate"), v("Agraciar", "To grace"),
            v("Agrupar", "To group"), v("Alargar", "To widen"),
            v("Alarmar", "To alarm"), v("Alfinetar", "To pin/prick"),
            v("Alinhar", "To align"), v("Almejar", "To aspire to"),
            v("Alocar", "To allocate"), v("Amadurecer", "To mature"),
            v("Amamentar", "To breastfeed"), v("Amarrar", "To tie up"),
            v("Ambicionar", "To aspire"), v("Amparar", "To support"),
            v("Ancorar", "To anchor"), v("Anoitecer", "To get dark"),
            v("Antever", "To foresee"), v("Apadrinhar", "To sponsor/godparent"),
            v("Aperfeiçoar", "To perfect"), v("Apetar", "To feel like"),
            v("Apoiar", "To support"), v("Apossar", "To seize"),
            v("Aprimorar", "To enhance"), v("Apurar", "To refine"),
            v("Arbitrar", "To arbitrate"), v("Armazenar", "To store"),
            v("Arquitetar", "To architect"), v("Articular", "To articulate"),
            v("Aspirar", "To aspirate/aspire"), v("Assaltar", "To assault"),
            v("Assar", "To roast"), v("Assessorar", "To advise"),
            v("Assimilar", "To assimilate"), v("Assobiar", "To whistle"),
            v("Atenuar", "To attenuate"), v("Aterrorizar", "To terrorize"),
            v("Atracar", "To dock"), v("Atropelar", "To run over"),
            v("Auxiliar", "To help"), v("Avariar", "To break down"),
            v("Balançar", "To balance/swing"), v("Barrar", "To block"),
            v("Basear", "To base"), v("Bifurcar", "To fork"),
            v("Bombardear", "To bomb"), v("Brotar", "To sprout"),
            v("Burlar", "To circumvent"), v("Caducar", "To expire"),
            v("Camuflar", "To camouflage"), v("Capitular", "To capitulate"),
            v("Caprichar", "To take great care"), v("Catalogar", "To catalog"),
            v("Centralizar", "To centralize"), v("Cifrar", "To encrypt"),
            v("Cimentar", "To cement"), v("Circular", "To circulate"),
            v("Civilizar", "To civilize"), v("Clarificar", "To clarify"),
            v("Climatizar", "To air-condition"), v("Coagir", "To coerce"),
            v("Cochichar", "To whisper"), v("Coincidir", "To coincide"),
            v("Colaborar", "To collaborate"), v("Colidir", "To collide"),
            v("Colonizar", "To colonize"), v("Comandar", "To command"),
            v("Comercializar", "To commercialize"), v("Cometer", "To commit (an act)"),
            v("Compactar", "To compact"), v("Compilar", "To compile"),
            v("Computar", "To compute"), v("Conceber", "To conceive"),
            v("Conceder", "To grant"), v("Conceituar", "To conceptualize"),
            v("Conciliar", "To reconcile"), v("Condicionar", "To condition"),
            v("Confeccionar", "To make/prepare"), v("Configurar", "To configure"),
            v("Confiscar", "To confiscate"), v("Confrontar", "To confront"),
            v("Congelar", "To freeze"), v("Congregar", "To congregate"),
            v("Conspirar", "To conspire"), v("Constar", "To be stated"),
            v("Consumar", "To consummate"), v("Contaminar", "To contaminate"),
            v("Contentar", "To content"), v("Contextualizar", "To contextualize"),
            v("Contornar", "To go around"), v("Convergir", "To converge"),
            v("Convocar", "To convene"), v("Coordenar", "To coordinate"),
            v("Coroar", "To crown"), v("Corresponder", "To correspond"),
            v("Creditar", "To credit"), v("Cristalizar", "To crystallize"),
            v("Crucificar", "To crucify"), v("Customizar", "To customize"),
            v("Debitar", "To debit"), v("Decifrar", "To decipher"),
            v("Decodificar", "To decode"), v("Decretar", "To decree"),
            v("Delinear", "To delineate"), v("Democratizar", "To democratize"),
            v("Demolir", "To demolish"), v("Denominar", "To denominate"),
            v("Depreciar", "To depreciate"), v("Deputar", "To depute"),
            v("Derivar", "To derive"), v("Derrapar", "To skid"),
            v("Desabar", "To collapse"), v("Desabotoar", "To unbutton"),
            v("Desagradar", "To displease"), v("Desamarrar", "To untie"),
            v("Desaprovar", "To disapprove"), v("Desarmar", "To disarm"),
            v("Desenvoltar", "To unwrap"), v("Desequilibrar", "To unbalance"),
            v("Desfazer", "To undo", true), v("Designar", "To designate"),
            v("Deslizar", "To slide"), v("Desmontar", "To disassemble"),
            v("Despachar", "To dispatch"), v("Desperdiçar", "To waste"),
            v("Despejar", "To pour/evict"), v("Desprezar", "To despise"),
            v("Destrancar", "To unlock"), v("Deteriorar", "To deteriorate"),
            v("Determinar", "To determine"), v("Diagnosticar", "To diagnose"),
            v("Digitalizar", "To digitize"), v("Diluir", "To dilute"),
            v("Diminuir", "To diminish"), v("Direcionar", "To direct"),
            v("Dirigir", "To drive/direct"), v("Disciplinar", "To discipline"),
            v("Discriminar", "To discriminate"), v("Discursar", "To give a speech"),
            v("Discutir", "To discuss"), v("Dispensar", "To dispense"),
            v("Dispersar", "To disperse"), v("Dispor", "To dispose", true),
            v("Disseminar", "To disseminate"), v("Dissolver", "To dissolve"),
            v("Distinguir", "To distinguish"), v("Distribuir", "To distribute"),
            v("Diversificar", "To diversify"), v("Dividir", "To divide"),
            v("Divulgar", "To disclose"), v("Documentar", "To document"),
            v("Domesticar", "To domesticate"), v("Dosificar", "To dose"),
            v("Dramatizar", "To dramatize"), v("Drenar", "To drain"),
            v("Duplicar", "To duplicate"), v("Durar", "To last"),
            v("Ecoar", "To echo"), v("Efetivar", "To make effective"),
            v("Eleger", "To elect"), v("Elevar", "To elevate"),
            v("Elogiar", "To praise"), v("Emancipar", "To emancipate"),
            v("Embaraçar", "To embarrass"), v("Embelezar", "To beautify"),
            v("Emigrar", "To emigrate"), v("Empacotar", "To pack"),
            v("Empalidecer", "To turn pale"), v("Empreender", "To undertake"),
            v("Encaixar", "To fit in"), v("Encaminhar", "To forward"),
            v("Encarar", "To face"), v("Encarregar", "To put in charge"),
            v("Encobrir", "To cover up"), v("Endossar", "To endorse"),
            v("Enfatizar", "To emphasize"), v("Enfraquecer", "To weaken"),
            v("Engajar", "To engage"), v("Engordar", "To fatten"),
            v("Enigmatizar", "To enigmatize"), v("Ensacar", "To bag"),
            v("Entrar", "To enter"), v("Entreter", "To entertain", true),
            v("Entristecer", "To sadden"), v("Enumerar", "To enumerate"),
            v("Envelhecer", "To age"), v("Envenenar", "To poison"),
            v("Enxergar", "To see/perceive"), v("Equilibrar", "To balance"),
            v("Equipar", "To equip"), v("Equivaler", "To be equivalent"),
            v("Escalar", "To climb"), v("Escandalizar", "To scandalize"),
            v("Escapar", "To escape"), v("Esclarecer", "To clarify"),
            v("Escoltar", "To escort"), v("Especializar", "To specialize"),
            v("Especificar", "To specify"), v("Especular", "To speculate"),
            v("Espelhar", "To mirror"), v("Espalhar", "To spread"),
            v("Esquentar", "To heat"), v("Estabilizar", "To stabilize"),
            v("Estacionar", "To park"), v("Estalear", "To crack"),
            v("Estipular", "To stipulate"), v("Estocar", "To stock"),
            v("Estourar", "To burst"), v("Esvaziar", "To empty"),
        ].sorted { $0.infinitive.localizedCompare($1.infinitive) == .orderedAscending }
    }
}

nonisolated struct GlossaryVerb: Codable, Sendable, Identifiable, Hashable {
    var id: String { infinitive.lowercased() }
    let infinitive: String
    let translation: String
    let irregular: Bool
}
