import Foundation

extension VerbDataService {
    static func buildLevels13to16() -> [Level] {
        let l13 = Level(level: 13, tense: "Presente Contínuo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Speaking right now", conjugations: .init(br: ["eu": "estou falando", "voce": "está falando", "nos": "estamos falando", "voces": "estão falando", "eles": "estão falando"], pt: ["eu": "estou a falar", "tu": "estás a falar", "ele": "está a falar", "nos": "estamos a falar", "vos": "estais a falar", "eles": "estão a falar"]), level: 13),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Eating right now", conjugations: .init(br: ["eu": "estou comendo", "voce": "está comendo", "nos": "estamos comendo", "voces": "estão comendo", "eles": "estão comendo"], pt: ["eu": "estou a comer", "tu": "estás a comer", "ele": "está a comer", "nos": "estamos a comer", "vos": "estais a comer", "eles": "estão a comer"]), level: 13),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "Writing right now", conjugations: .init(br: ["eu": "estou escrevendo", "voce": "está escrevendo", "nos": "estamos escrevendo", "voces": "estão escrevendo", "eles": "estão escrevendo"], pt: ["eu": "estou a escrever", "tu": "estás a escrever", "ele": "está a escrever", "nos": "estamos a escrever", "vos": "estais a escrever", "eles": "estão a escrever"]), level: 13),
            Verb(infinitive: "Dormir", translation: "To sleep", irregular: true, context: "Sleeping right now", conjugations: .init(br: ["eu": "estou dormindo", "voce": "está dormindo", "nos": "estamos dormindo", "voces": "estão dormindo", "eles": "estão dormindo"], pt: ["eu": "estou a dormir", "tu": "estás a dormir", "ele": "está a dormir", "nos": "estamos a dormir", "vos": "estais a dormir", "eles": "estão a dormir"]), level: 13),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Working right now", conjugations: .init(br: ["eu": "estou trabalhando", "voce": "está trabalhando", "nos": "estamos trabalhando", "voces": "estão trabalhando", "eles": "estão trabalhando"], pt: ["eu": "estou a trabalhar", "tu": "estás a trabalhar", "ele": "está a trabalhar", "nos": "estamos a trabalhar", "vos": "estais a trabalhar", "eles": "estão a trabalhar"]), level: 13)
        ])

        let l14 = Level(level: 14, tense: "Presente Contínuo", verbs: [
            Verb(infinitive: "Ler", translation: "To read", irregular: true, context: "Reading right now", conjugations: .init(br: ["eu": "estou lendo", "voce": "está lendo", "nos": "estamos lendo", "voces": "estão lendo", "eles": "estão lendo"], pt: ["eu": "estou a ler", "tu": "estás a ler", "ele": "está a ler", "nos": "estamos a ler", "vos": "estais a ler", "eles": "estão a ler"]), level: 14),
            Verb(infinitive: "Correr", translation: "To run", irregular: false, context: "Running right now", conjugations: .init(br: ["eu": "estou correndo", "voce": "está correndo", "nos": "estamos correndo", "voces": "estão correndo", "eles": "estão correndo"], pt: ["eu": "estou a correr", "tu": "estás a correr", "ele": "está a correr", "nos": "estamos a correr", "vos": "estais a correr", "eles": "estão a correr"]), level: 14),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Doing right now", conjugations: .init(br: ["eu": "estou fazendo", "voce": "está fazendo", "nos": "estamos fazendo", "voces": "estão fazendo", "eles": "estão fazendo"], pt: ["eu": "estou a fazer", "tu": "estás a fazer", "ele": "está a fazer", "nos": "estamos a fazer", "vos": "estais a fazer", "eles": "estão a fazer"]), level: 14),
            Verb(infinitive: "Estudar", translation: "To study", irregular: false, context: "Studying right now", conjugations: .init(br: ["eu": "estou estudando", "voce": "está estudando", "nos": "estamos estudando", "voces": "estão estudando", "eles": "estão estudando"], pt: ["eu": "estou a estudar", "tu": "estás a estudar", "ele": "está a estudar", "nos": "estamos a estudar", "vos": "estais a estudar", "eles": "estão a estudar"]), level: 14),
            Verb(infinitive: "Viajar", translation: "To travel", irregular: false, context: "Traveling right now", conjugations: .init(br: ["eu": "estou viajando", "voce": "está viajando", "nos": "estamos viajando", "voces": "estão viajando", "eles": "estão viajando"], pt: ["eu": "estou a viajar", "tu": "estás a viajar", "ele": "está a viajar", "nos": "estamos a viajar", "vos": "estais a viajar", "eles": "estão a viajar"]), level: 14)
        ])

        let l15 = Level(level: 15, tense: "Reflexivos", verbs: [
            Verb(infinitive: "Vestir-se", translation: "To get dressed", irregular: true, context: "Getting dressed", conjugations: .init(br: ["eu": "me visto", "voce": "se veste", "nos": "nos vestimos", "voces": "se vestem", "eles": "se vestem"], pt: ["eu": "visto-me", "tu": "vestes-te", "ele": "veste-se", "nos": "vestimo-nos", "vos": "vestis-vos", "eles": "vestem-se"]), level: 15),
            Verb(infinitive: "Lavar-se", translation: "To wash oneself", irregular: false, context: "Washing up", conjugations: .init(br: ["eu": "me lavo", "voce": "se lava", "nos": "nos lavamos", "voces": "se lavam", "eles": "se lavam"], pt: ["eu": "lavo-me", "tu": "lavas-te", "ele": "lava-se", "nos": "lavamo-nos", "vos": "lavais-vos", "eles": "lavam-se"]), level: 15),
            Verb(infinitive: "Sentar-se", translation: "To sit down", irregular: false, context: "Sitting", conjugations: .init(br: ["eu": "me sento", "voce": "se senta", "nos": "nos sentamos", "voces": "se sentam", "eles": "se sentam"], pt: ["eu": "sento-me", "tu": "sentas-te", "ele": "senta-se", "nos": "sentamo-nos", "vos": "sentais-vos", "eles": "sentam-se"]), level: 15),
            Verb(infinitive: "Deitar-se", translation: "To lie down", irregular: false, context: "Going to bed", conjugations: .init(br: ["eu": "me deito", "voce": "se deita", "nos": "nos deitamos", "voces": "se deitam", "eles": "se deitam"], pt: ["eu": "deito-me", "tu": "deitas-te", "ele": "deita-se", "nos": "deitamo-nos", "vos": "deitais-vos", "eles": "deitam-se"]), level: 15),
            Verb(infinitive: "Levantar-se", translation: "To get up", irregular: false, context: "Waking up", conjugations: .init(br: ["eu": "me levanto", "voce": "se levanta", "nos": "nos levantamos", "voces": "se levantam", "eles": "se levantam"], pt: ["eu": "levanto-me", "tu": "levantas-te", "ele": "levanta-se", "nos": "levantamo-nos", "vos": "levantais-vos", "eles": "levantam-se"]), level: 15)
        ])

        let l16 = Level(level: 16, tense: "Reflexivos", verbs: [
            Verb(infinitive: "Chamar-se", translation: "To be called", irregular: false, context: "Introductions", conjugations: .init(br: ["eu": "me chamo", "voce": "se chama", "nos": "nos chamamos", "voces": "se chamam", "eles": "se chamam"], pt: ["eu": "chamo-me", "tu": "chamas-te", "ele": "chama-se", "nos": "chamamo-nos", "vos": "chamais-vos", "eles": "chamam-se"]), level: 16),
            Verb(infinitive: "Lembrar-se", translation: "To remember", irregular: false, context: "Remembering", conjugations: .init(br: ["eu": "me lembro", "voce": "se lembra", "nos": "nos lembramos", "voces": "se lembram", "eles": "se lembram"], pt: ["eu": "lembro-me", "tu": "lembras-te", "ele": "lembra-se", "nos": "lembramo-nos", "vos": "lembrais-vos", "eles": "lembram-se"]), level: 16),
            Verb(infinitive: "Divertir-se", translation: "To have fun", irregular: true, context: "Enjoying oneself", conjugations: .init(br: ["eu": "me divirto", "voce": "se diverte", "nos": "nos divertimos", "voces": "se divertem", "eles": "se divertem"], pt: ["eu": "divirto-me", "tu": "divertes-te", "ele": "diverte-se", "nos": "divertimo-nos", "vos": "divertis-vos", "eles": "divertem-se"]), level: 16),
            Verb(infinitive: "Preocupar-se", translation: "To worry", irregular: false, context: "Worrying", conjugations: .init(br: ["eu": "me preocupo", "voce": "se preocupa", "nos": "nos preocupamos", "voces": "se preocupam", "eles": "se preocupam"], pt: ["eu": "preocupo-me", "tu": "preocupas-te", "ele": "preocupa-se", "nos": "preocupamo-nos", "vos": "preocupais-vos", "eles": "preocupam-se"]), level: 16)
        ])

        return [l13, l14, l15, l16]
    }
}
