import Foundation

@Observable
@MainActor
class VerbDataService {
    private(set) var levels: [Level] = []
    private(set) var isLoaded: Bool = false

    init() {
        loadLevels()
    }

    func loadLevels() {
        levels = Self.buildAllLevels()
        isLoaded = true
    }

    func level(for number: Int) -> Level? {
        levels.first { $0.level == number }
    }

    func verbs(forLevel number: Int) -> [Verb] {
        level(for: number)?.verbs ?? []
    }

    func allSortedLevels() -> [Level] {
        levels.sorted { $0.level < $1.level }
    }

    private static func buildAllLevels() -> [Level] {
        var result: [Level] = []

        // MARK: - Level 1: Presente — Regular -AR/-ER basics
        result.append(Level(level: 1, tense: "Presente", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "General conversation", conjugations: .init(br: ["eu": "falo", "voce": "fala", "nos": "falamos", "voces": "falam", "eles": "falam"], pt: ["eu": "falo", "tu": "falas", "ele": "fala", "nos": "falamos", "vos": "falais", "eles": "falam"]), level: 1),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Food and meals", conjugations: .init(br: ["eu": "como", "voce": "come", "nos": "comemos", "voces": "comem", "eles": "comem"], pt: ["eu": "como", "tu": "comes", "ele": "come", "nos": "comemos", "vos": "comeis", "eles": "comem"]), level: 1),
            Verb(infinitive: "Morar", translation: "To live/reside", irregular: false, context: "Where you live", conjugations: .init(br: ["eu": "moro", "voce": "mora", "nos": "moramos", "voces": "moram", "eles": "moram"], pt: ["eu": "moro", "tu": "moras", "ele": "mora", "nos": "moramos", "vos": "morais", "eles": "moram"]), level: 1),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Jobs and professions", conjugations: .init(br: ["eu": "trabalho", "voce": "trabalha", "nos": "trabalhamos", "voces": "trabalham", "eles": "trabalham"], pt: ["eu": "trabalho", "tu": "trabalhas", "ele": "trabalha", "nos": "trabalhamos", "vos": "trabalhais", "eles": "trabalham"]), level: 1),
            Verb(infinitive: "Andar", translation: "To walk", irregular: false, context: "Movement on foot", conjugations: .init(br: ["eu": "ando", "voce": "anda", "nos": "andamos", "voces": "andam", "eles": "andam"], pt: ["eu": "ando", "tu": "andas", "ele": "anda", "nos": "andamos", "vos": "andais", "eles": "andam"]), level: 1),
            Verb(infinitive: "Chamar", translation: "To call", irregular: false, context: "Names and calling", conjugations: .init(br: ["eu": "chamo", "voce": "chama", "nos": "chamamos", "voces": "chamam", "eles": "chamam"], pt: ["eu": "chamo", "tu": "chamas", "ele": "chama", "nos": "chamamos", "vos": "chamais", "eles": "chamam"]), level: 1)
        ]))

        // MARK: - Level 2: Presente — Key irregulars
        result.append(Level(level: 2, tense: "Presente", verbs: [
            Verb(infinitive: "Ser", translation: "To be (permanent)", irregular: true, context: "Identity and characteristics", conjugations: .init(br: ["eu": "sou", "voce": "é", "nos": "somos", "voces": "são", "eles": "são"], pt: ["eu": "sou", "tu": "és", "ele": "é", "nos": "somos", "vos": "sois", "eles": "são"]), level: 2),
            Verb(infinitive: "Estar", translation: "To be (temporary)", irregular: true, context: "States and locations", conjugations: .init(br: ["eu": "estou", "voce": "está", "nos": "estamos", "voces": "estão", "eles": "estão"], pt: ["eu": "estou", "tu": "estás", "ele": "está", "nos": "estamos", "vos": "estais", "eles": "estão"]), level: 2),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Possession and obligations", conjugations: .init(br: ["eu": "tenho", "voce": "tem", "nos": "temos", "voces": "têm", "eles": "têm"], pt: ["eu": "tenho", "tu": "tens", "ele": "tem", "nos": "temos", "vos": "tendes", "eles": "têm"]), level: 2),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Movement and future plans", conjugations: .init(br: ["eu": "vou", "voce": "vai", "nos": "vamos", "voces": "vão", "eles": "vão"], pt: ["eu": "vou", "tu": "vais", "ele": "vai", "nos": "vamos", "vos": "ides", "eles": "vão"]), level: 2),
            Verb(infinitive: "Haver", translation: "To exist/there is", irregular: true, context: "Existence", conjugations: .init(br: ["eu": "hei", "voce": "há", "nos": "havemos", "voces": "hão", "eles": "hão"], pt: ["eu": "hei", "tu": "hás", "ele": "há", "nos": "havemos", "vos": "haveis", "eles": "hão"]), level: 2)
        ]))

        // MARK: - Level 3: Presente — Power verbs
        result.append(Level(level: 3, tense: "Presente", verbs: [
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Actions and creation", conjugations: .init(br: ["eu": "faço", "voce": "faz", "nos": "fazemos", "voces": "fazem", "eles": "fazem"], pt: ["eu": "faço", "tu": "fazes", "ele": "faz", "nos": "fazemos", "vos": "fazeis", "eles": "fazem"]), level: 3),
            Verb(infinitive: "Poder", translation: "To be able/can", irregular: true, context: "Ability and permission", conjugations: .init(br: ["eu": "posso", "voce": "pode", "nos": "podemos", "voces": "podem", "eles": "podem"], pt: ["eu": "posso", "tu": "podes", "ele": "pode", "nos": "podemos", "vos": "podeis", "eles": "podem"]), level: 3),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "Desires and wishes", conjugations: .init(br: ["eu": "quero", "voce": "quer", "nos": "queremos", "voces": "querem", "eles": "querem"], pt: ["eu": "quero", "tu": "queres", "ele": "quer", "nos": "queremos", "vos": "quereis", "eles": "querem"]), level: 3),
            Verb(infinitive: "Saber", translation: "To know (facts)", irregular: true, context: "Knowledge and skills", conjugations: .init(br: ["eu": "sei", "voce": "sabe", "nos": "sabemos", "voces": "sabem", "eles": "sabem"], pt: ["eu": "sei", "tu": "sabes", "ele": "sabe", "nos": "sabemos", "vos": "sabeis", "eles": "sabem"]), level: 3),
            Verb(infinitive: "Dever", translation: "To must/owe", irregular: false, context: "Obligation", conjugations: .init(br: ["eu": "devo", "voce": "deve", "nos": "devemos", "voces": "devem", "eles": "devem"], pt: ["eu": "devo", "tu": "deves", "ele": "deve", "nos": "devemos", "vos": "deveis", "eles": "devem"]), level: 3)
        ]))

        // MARK: - Level 4: Presente — Communication verbs
        result.append(Level(level: 4, tense: "Presente", verbs: [
            Verb(infinitive: "Dizer", translation: "To say/tell", irregular: true, context: "Communication", conjugations: .init(br: ["eu": "digo", "voce": "diz", "nos": "dizemos", "voces": "dizem", "eles": "dizem"], pt: ["eu": "digo", "tu": "dizes", "ele": "diz", "nos": "dizemos", "vos": "dizeis", "eles": "dizem"]), level: 4),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "Sight and perception", conjugations: .init(br: ["eu": "vejo", "voce": "vê", "nos": "vemos", "voces": "veem", "eles": "veem"], pt: ["eu": "vejo", "tu": "vês", "ele": "vê", "nos": "vemos", "vos": "vedes", "eles": "veem"]), level: 4),
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "Giving and offering", conjugations: .init(br: ["eu": "dou", "voce": "dá", "nos": "damos", "voces": "dão", "eles": "dão"], pt: ["eu": "dou", "tu": "dás", "ele": "dá", "nos": "damos", "vos": "dais", "eles": "dão"]), level: 4),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "Arrival and movement", conjugations: .init(br: ["eu": "venho", "voce": "vem", "nos": "vimos", "voces": "vêm", "eles": "vêm"], pt: ["eu": "venho", "tu": "vens", "ele": "vem", "nos": "vimos", "vos": "vindes", "eles": "vêm"]), level: 4),
            Verb(infinitive: "Pôr", translation: "To put/place", irregular: true, context: "Placing objects", conjugations: .init(br: ["eu": "ponho", "voce": "põe", "nos": "pomos", "voces": "põem", "eles": "põem"], pt: ["eu": "ponho", "tu": "pões", "ele": "põe", "nos": "pomos", "vos": "pondes", "eles": "põem"]), level: 4)
        ]))

        // MARK: - Level 5: Presente — Everyday regular
        result.append(Level(level: 5, tense: "Presente", verbs: [
            Verb(infinitive: "Estudar", translation: "To study", irregular: false, context: "Education and learning", conjugations: .init(br: ["eu": "estudo", "voce": "estuda", "nos": "estudamos", "voces": "estudam", "eles": "estudam"], pt: ["eu": "estudo", "tu": "estudas", "ele": "estuda", "nos": "estudamos", "vos": "estudais", "eles": "estudam"]), level: 5),
            Verb(infinitive: "Gostar", translation: "To like", irregular: false, context: "Preferences and enjoyment", conjugations: .init(br: ["eu": "gosto", "voce": "gosta", "nos": "gostamos", "voces": "gostam", "eles": "gostam"], pt: ["eu": "gosto", "tu": "gostas", "ele": "gosta", "nos": "gostamos", "vos": "gostais", "eles": "gostam"]), level: 5),
            Verb(infinitive: "Precisar", translation: "To need", irregular: false, context: "Necessities", conjugations: .init(br: ["eu": "preciso", "voce": "precisa", "nos": "precisamos", "voces": "precisam", "eles": "precisam"], pt: ["eu": "preciso", "tu": "precisas", "ele": "precisa", "nos": "precisamos", "vos": "precisais", "eles": "precisam"]), level: 5),
            Verb(infinitive: "Comprar", translation: "To buy", irregular: false, context: "Shopping and transactions", conjugations: .init(br: ["eu": "compro", "voce": "compra", "nos": "compramos", "voces": "compram", "eles": "compram"], pt: ["eu": "compro", "tu": "compras", "ele": "compra", "nos": "compramos", "vos": "comprais", "eles": "compram"]), level: 5),
            Verb(infinitive: "Ajudar", translation: "To help", irregular: false, context: "Assistance", conjugations: .init(br: ["eu": "ajudo", "voce": "ajuda", "nos": "ajudamos", "voces": "ajudam", "eles": "ajudam"], pt: ["eu": "ajudo", "tu": "ajudas", "ele": "ajuda", "nos": "ajudamos", "vos": "ajudais", "eles": "ajudam"]), level: 5),
            Verb(infinitive: "Pagar", translation: "To pay", irregular: false, context: "Transactions", conjugations: .init(br: ["eu": "pago", "voce": "paga", "nos": "pagamos", "voces": "pagam", "eles": "pagam"], pt: ["eu": "pago", "tu": "pagas", "ele": "paga", "nos": "pagamos", "vos": "pagais", "eles": "pagam"]), level: 5)
        ]))

        // MARK: - Level 6: Presente — -ER/-IR patterns
        result.append(Level(level: 6, tense: "Presente", verbs: [
            Verb(infinitive: "Abrir", translation: "To open", irregular: false, context: "Opening things", conjugations: .init(br: ["eu": "abro", "voce": "abre", "nos": "abrimos", "voces": "abrem", "eles": "abrem"], pt: ["eu": "abro", "tu": "abres", "ele": "abre", "nos": "abrimos", "vos": "abris", "eles": "abrem"]), level: 6),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "Writing and communication", conjugations: .init(br: ["eu": "escrevo", "voce": "escreve", "nos": "escrevemos", "voces": "escrevem", "eles": "escrevem"], pt: ["eu": "escrevo", "tu": "escreves", "ele": "escreve", "nos": "escrevemos", "vos": "escreveis", "eles": "escrevem"]), level: 6),
            Verb(infinitive: "Beber", translation: "To drink", irregular: false, context: "Drinking beverages", conjugations: .init(br: ["eu": "bebo", "voce": "bebe", "nos": "bebemos", "voces": "bebem", "eles": "bebem"], pt: ["eu": "bebo", "tu": "bebes", "ele": "bebe", "nos": "bebemos", "vos": "bebeis", "eles": "bebem"]), level: 6),
            Verb(infinitive: "Partir", translation: "To leave/depart", irregular: false, context: "Departures and travel", conjugations: .init(br: ["eu": "parto", "voce": "parte", "nos": "partimos", "voces": "partem", "eles": "partem"], pt: ["eu": "parto", "tu": "partes", "ele": "parte", "nos": "partimos", "vos": "partis", "eles": "partem"]), level: 6),
            Verb(infinitive: "Vender", translation: "To sell", irregular: false, context: "Commerce", conjugations: .init(br: ["eu": "vendo", "voce": "vende", "nos": "vendemos", "voces": "vendem", "eles": "vendem"], pt: ["eu": "vendo", "tu": "vendes", "ele": "vende", "nos": "vendemos", "vos": "vendeis", "eles": "vendem"]), level: 6),
            Verb(infinitive: "Decidir", translation: "To decide", irregular: false, context: "Making decisions", conjugations: .init(br: ["eu": "decido", "voce": "decide", "nos": "decidimos", "voces": "decidem", "eles": "decidem"], pt: ["eu": "decido", "tu": "decides", "ele": "decide", "nos": "decidimos", "vos": "decidis", "eles": "decidem"]), level: 6)
        ]))

        // MARK: - Level 7: Presente — Thought & emotion
        result.append(Level(level: 7, tense: "Presente", verbs: [
            Verb(infinitive: "Pensar", translation: "To think", irregular: false, context: "Thoughts and opinions", conjugations: .init(br: ["eu": "penso", "voce": "pensa", "nos": "pensamos", "voces": "pensam", "eles": "pensam"], pt: ["eu": "penso", "tu": "pensas", "ele": "pensa", "nos": "pensamos", "vos": "pensais", "eles": "pensam"]), level: 7),
            Verb(infinitive: "Sentir", translation: "To feel", irregular: true, context: "Emotions and senses", conjugations: .init(br: ["eu": "sinto", "voce": "sente", "nos": "sentimos", "voces": "sentem", "eles": "sentem"], pt: ["eu": "sinto", "tu": "sentes", "ele": "sente", "nos": "sentimos", "vos": "sentis", "eles": "sentem"]), level: 7),
            Verb(infinitive: "Acreditar", translation: "To believe", irregular: false, context: "Beliefs and faith", conjugations: .init(br: ["eu": "acredito", "voce": "acredita", "nos": "acreditamos", "voces": "acreditam", "eles": "acreditam"], pt: ["eu": "acredito", "tu": "acreditas", "ele": "acredita", "nos": "acreditamos", "vos": "acreditais", "eles": "acreditam"]), level: 7),
            Verb(infinitive: "Lembrar", translation: "To remember", irregular: false, context: "Memory", conjugations: .init(br: ["eu": "lembro", "voce": "lembra", "nos": "lembramos", "voces": "lembram", "eles": "lembram"], pt: ["eu": "lembro", "tu": "lembras", "ele": "lembra", "nos": "lembramos", "vos": "lembrais", "eles": "lembram"]), level: 7),
            Verb(infinitive: "Esquecer", translation: "To forget", irregular: false, context: "Forgetting", conjugations: .init(br: ["eu": "esqueço", "voce": "esquece", "nos": "esquecemos", "voces": "esquecem", "eles": "esquecem"], pt: ["eu": "esqueço", "tu": "esqueces", "ele": "esquece", "nos": "esquecemos", "vos": "esqueceis", "eles": "esquecem"]), level: 7)
        ]))

        // MARK: - Level 8: Presente — Daily routines
        result.append(Level(level: 8, tense: "Presente", verbs: [
            Verb(infinitive: "Dormir", translation: "To sleep", irregular: true, context: "Rest and sleep", conjugations: .init(br: ["eu": "durmo", "voce": "dorme", "nos": "dormimos", "voces": "dormem", "eles": "dormem"], pt: ["eu": "durmo", "tu": "dormes", "ele": "dorme", "nos": "dormimos", "vos": "dormis", "eles": "dormem"]), level: 8),
            Verb(infinitive: "Acordar", translation: "To wake up", irregular: false, context: "Morning routine", conjugations: .init(br: ["eu": "acordo", "voce": "acorda", "nos": "acordamos", "voces": "acordam", "eles": "acordam"], pt: ["eu": "acordo", "tu": "acordas", "ele": "acorda", "nos": "acordamos", "vos": "acordais", "eles": "acordam"]), level: 8),
            Verb(infinitive: "Tomar", translation: "To take/have", irregular: false, context: "Meals and showers", conjugations: .init(br: ["eu": "tomo", "voce": "toma", "nos": "tomamos", "voces": "tomam", "eles": "tomam"], pt: ["eu": "tomo", "tu": "tomas", "ele": "toma", "nos": "tomamos", "vos": "tomais", "eles": "tomam"]), level: 8),
            Verb(infinitive: "Sair", translation: "To leave/go out", irregular: true, context: "Going out", conjugations: .init(br: ["eu": "saio", "voce": "sai", "nos": "saímos", "voces": "saem", "eles": "saem"], pt: ["eu": "saio", "tu": "sais", "ele": "sai", "nos": "saímos", "vos": "saís", "eles": "saem"]), level: 8),
            Verb(infinitive: "Chegar", translation: "To arrive", irregular: false, context: "Arrival", conjugations: .init(br: ["eu": "chego", "voce": "chega", "nos": "chegamos", "voces": "chegam", "eles": "chegam"], pt: ["eu": "chego", "tu": "chegas", "ele": "chega", "nos": "chegamos", "vos": "chegais", "eles": "chegam"]), level: 8),
            Verb(infinitive: "Voltar", translation: "To return", irregular: false, context: "Coming back", conjugations: .init(br: ["eu": "volto", "voce": "volta", "nos": "voltamos", "voces": "voltam", "eles": "voltam"], pt: ["eu": "volto", "tu": "voltas", "ele": "volta", "nos": "voltamos", "vos": "voltais", "eles": "voltam"]), level: 8)
        ]))

        // MARK: - Level 9: Presente — Social interactions
        result.append(Level(level: 9, tense: "Presente", verbs: [
            Verb(infinitive: "Conhecer", translation: "To know (people)", irregular: false, context: "Knowing people/places", conjugations: .init(br: ["eu": "conheço", "voce": "conhece", "nos": "conhecemos", "voces": "conhecem", "eles": "conhecem"], pt: ["eu": "conheço", "tu": "conheces", "ele": "conhece", "nos": "conhecemos", "vos": "conheceis", "eles": "conhecem"]), level: 9),
            Verb(infinitive: "Encontrar", translation: "To find/meet", irregular: false, context: "Meeting people", conjugations: .init(br: ["eu": "encontro", "voce": "encontra", "nos": "encontramos", "voces": "encontram", "eles": "encontram"], pt: ["eu": "encontro", "tu": "encontras", "ele": "encontra", "nos": "encontramos", "vos": "encontrais", "eles": "encontram"]), level: 9),
            Verb(infinitive: "Pedir", translation: "To ask for", irregular: true, context: "Requests and orders", conjugations: .init(br: ["eu": "peço", "voce": "pede", "nos": "pedimos", "voces": "pedem", "eles": "pedem"], pt: ["eu": "peço", "tu": "pedes", "ele": "pede", "nos": "pedimos", "vos": "pedis", "eles": "pedem"]), level: 9),
            Verb(infinitive: "Esperar", translation: "To wait/hope", irregular: false, context: "Waiting and hoping", conjugations: .init(br: ["eu": "espero", "voce": "espera", "nos": "esperamos", "voces": "esperam", "eles": "esperam"], pt: ["eu": "espero", "tu": "esperas", "ele": "espera", "nos": "esperamos", "vos": "esperais", "eles": "esperam"]), level: 9),
            Verb(infinitive: "Ouvir", translation: "To hear/listen", irregular: true, context: "Listening", conjugations: .init(br: ["eu": "ouço", "voce": "ouve", "nos": "ouvimos", "voces": "ouvem", "eles": "ouvem"], pt: ["eu": "ouço", "tu": "ouves", "ele": "ouve", "nos": "ouvimos", "vos": "ouvis", "eles": "ouvem"]), level: 9)
        ]))

        // MARK: - Level 10: Presente — Home & lifestyle
        result.append(Level(level: 10, tense: "Presente", verbs: [
            Verb(infinitive: "Cozinhar", translation: "To cook", irregular: false, context: "Cooking", conjugations: .init(br: ["eu": "cozinho", "voce": "cozinha", "nos": "cozinhamos", "voces": "cozinham", "eles": "cozinham"], pt: ["eu": "cozinho", "tu": "cozinhas", "ele": "cozinha", "nos": "cozinhamos", "vos": "cozinhais", "eles": "cozinham"]), level: 10),
            Verb(infinitive: "Limpar", translation: "To clean", irregular: false, context: "Cleaning", conjugations: .init(br: ["eu": "limpo", "voce": "limpa", "nos": "limpamos", "voces": "limpam", "eles": "limpam"], pt: ["eu": "limpo", "tu": "limpas", "ele": "limpa", "nos": "limpamos", "vos": "limpais", "eles": "limpam"]), level: 10),
            Verb(infinitive: "Jogar", translation: "To play (games)", irregular: false, context: "Games and sports", conjugations: .init(br: ["eu": "jogo", "voce": "joga", "nos": "jogamos", "voces": "jogam", "eles": "jogam"], pt: ["eu": "jogo", "tu": "jogas", "ele": "joga", "nos": "jogamos", "vos": "jogais", "eles": "jogam"]), level: 10),
            Verb(infinitive: "Ler", translation: "To read", irregular: true, context: "Reading", conjugations: .init(br: ["eu": "leio", "voce": "lê", "nos": "lemos", "voces": "leem", "eles": "leem"], pt: ["eu": "leio", "tu": "lês", "ele": "lê", "nos": "lemos", "vos": "ledes", "eles": "leem"]), level: 10),
            Verb(infinitive: "Correr", translation: "To run", irregular: false, context: "Exercise and running", conjugations: .init(br: ["eu": "corro", "voce": "corre", "nos": "corremos", "voces": "correm", "eles": "correm"], pt: ["eu": "corro", "tu": "corres", "ele": "corre", "nos": "corremos", "vos": "correis", "eles": "correm"]), level: 10)
        ]))

        // MARK: - Level 11: Presente — Travel & directions
        result.append(Level(level: 11, tense: "Presente", verbs: [
            Verb(infinitive: "Viajar", translation: "To travel", irregular: false, context: "Travel", conjugations: .init(br: ["eu": "viajo", "voce": "viaja", "nos": "viajamos", "voces": "viajam", "eles": "viajam"], pt: ["eu": "viajo", "tu": "viajas", "ele": "viaja", "nos": "viajamos", "vos": "viajais", "eles": "viajam"]), level: 11),
            Verb(infinitive: "Ficar", translation: "To stay/remain", irregular: false, context: "Staying somewhere", conjugations: .init(br: ["eu": "fico", "voce": "fica", "nos": "ficamos", "voces": "ficam", "eles": "ficam"], pt: ["eu": "fico", "tu": "ficas", "ele": "fica", "nos": "ficamos", "vos": "ficais", "eles": "ficam"]), level: 11),
            Verb(infinitive: "Levar", translation: "To take/carry", irregular: false, context: "Carrying things", conjugations: .init(br: ["eu": "levo", "voce": "leva", "nos": "levamos", "voces": "levam", "eles": "levam"], pt: ["eu": "levo", "tu": "levas", "ele": "leva", "nos": "levamos", "vos": "levais", "eles": "levam"]), level: 11),
            Verb(infinitive: "Trazer", translation: "To bring", irregular: true, context: "Bringing things", conjugations: .init(br: ["eu": "trago", "voce": "traz", "nos": "trazemos", "voces": "trazem", "eles": "trazem"], pt: ["eu": "trago", "tu": "trazes", "ele": "traz", "nos": "trazemos", "vos": "trazeis", "eles": "trazem"]), level: 11),
            Verb(infinitive: "Mostrar", translation: "To show", irregular: false, context: "Showing and demonstrating", conjugations: .init(br: ["eu": "mostro", "voce": "mostra", "nos": "mostramos", "voces": "mostram", "eles": "mostram"], pt: ["eu": "mostro", "tu": "mostras", "ele": "mostra", "nos": "mostramos", "vos": "mostrais", "eles": "mostram"]), level: 11)
        ]))

        // MARK: - Level 12: Presente — Emotions & states
        result.append(Level(level: 12, tense: "Presente", verbs: [
            Verb(infinitive: "Amar", translation: "To love", irregular: false, context: "Love and affection", conjugations: .init(br: ["eu": "amo", "voce": "ama", "nos": "amamos", "voces": "amam", "eles": "amam"], pt: ["eu": "amo", "tu": "amas", "ele": "ama", "nos": "amamos", "vos": "amais", "eles": "amam"]), level: 12),
            Verb(infinitive: "Preferir", translation: "To prefer", irregular: true, context: "Preferences", conjugations: .init(br: ["eu": "prefiro", "voce": "prefere", "nos": "preferimos", "voces": "preferem", "eles": "preferem"], pt: ["eu": "prefiro", "tu": "preferes", "ele": "prefere", "nos": "preferimos", "vos": "preferis", "eles": "preferem"]), level: 12),
            Verb(infinitive: "Parecer", translation: "To seem/appear", irregular: false, context: "Appearances", conjugations: .init(br: ["eu": "pareço", "voce": "parece", "nos": "parecemos", "voces": "parecem", "eles": "parecem"], pt: ["eu": "pareço", "tu": "pareces", "ele": "parece", "nos": "parecemos", "vos": "pareceis", "eles": "parecem"]), level: 12),
            Verb(infinitive: "Conseguir", translation: "To manage/achieve", irregular: true, context: "Achievement", conjugations: .init(br: ["eu": "consigo", "voce": "consegue", "nos": "conseguimos", "voces": "conseguem", "eles": "conseguem"], pt: ["eu": "consigo", "tu": "consegues", "ele": "consegue", "nos": "conseguimos", "vos": "conseguis", "eles": "conseguem"]), level: 12),
            Verb(infinitive: "Entender", translation: "To understand", irregular: false, context: "Comprehension", conjugations: .init(br: ["eu": "entendo", "voce": "entende", "nos": "entendemos", "voces": "entendem", "eles": "entendem"], pt: ["eu": "entendo", "tu": "entendes", "ele": "entende", "nos": "entendemos", "vos": "entendeis", "eles": "entendem"]), level: 12)
        ]))

        // MARK: - Level 13: Presente Contínuo
        result.append(Level(level: 13, tense: "Presente Contínuo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Speaking right now", conjugations: .init(br: ["eu": "estou falando", "voce": "está falando", "nos": "estamos falando", "voces": "estão falando", "eles": "estão falando"], pt: ["eu": "estou a falar", "tu": "estás a falar", "ele": "está a falar", "nos": "estamos a falar", "vos": "estais a falar", "eles": "estão a falar"]), level: 13),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Eating right now", conjugations: .init(br: ["eu": "estou comendo", "voce": "está comendo", "nos": "estamos comendo", "voces": "estão comendo", "eles": "estão comendo"], pt: ["eu": "estou a comer", "tu": "estás a comer", "ele": "está a comer", "nos": "estamos a comer", "vos": "estais a comer", "eles": "estão a comer"]), level: 13),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "Writing right now", conjugations: .init(br: ["eu": "estou escrevendo", "voce": "está escrevendo", "nos": "estamos escrevendo", "voces": "estão escrevendo", "eles": "estão escrevendo"], pt: ["eu": "estou a escrever", "tu": "estás a escrever", "ele": "está a escrever", "nos": "estamos a escrever", "vos": "estais a escrever", "eles": "estão a escrever"]), level: 13),
            Verb(infinitive: "Dormir", translation: "To sleep", irregular: true, context: "Sleeping right now", conjugations: .init(br: ["eu": "estou dormindo", "voce": "está dormindo", "nos": "estamos dormindo", "voces": "estão dormindo", "eles": "estão dormindo"], pt: ["eu": "estou a dormir", "tu": "estás a dormir", "ele": "está a dormir", "nos": "estamos a dormir", "vos": "estais a dormir", "eles": "estão a dormir"]), level: 13),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Working right now", conjugations: .init(br: ["eu": "estou trabalhando", "voce": "está trabalhando", "nos": "estamos trabalhando", "voces": "estão trabalhando", "eles": "estão trabalhando"], pt: ["eu": "estou a trabalhar", "tu": "estás a trabalhar", "ele": "está a trabalhar", "nos": "estamos a trabalhar", "vos": "estais a trabalhar", "eles": "estão a trabalhar"]), level: 13)
        ]))

        // MARK: - Level 14: Presente Contínuo 2
        result.append(Level(level: 14, tense: "Presente Contínuo", verbs: [
            Verb(infinitive: "Ler", translation: "To read", irregular: true, context: "Reading right now", conjugations: .init(br: ["eu": "estou lendo", "voce": "está lendo", "nos": "estamos lendo", "voces": "estão lendo", "eles": "estão lendo"], pt: ["eu": "estou a ler", "tu": "estás a ler", "ele": "está a ler", "nos": "estamos a ler", "vos": "estais a ler", "eles": "estão a ler"]), level: 14),
            Verb(infinitive: "Correr", translation: "To run", irregular: false, context: "Running right now", conjugations: .init(br: ["eu": "estou correndo", "voce": "está correndo", "nos": "estamos correndo", "voces": "estão correndo", "eles": "estão correndo"], pt: ["eu": "estou a correr", "tu": "estás a correr", "ele": "está a correr", "nos": "estamos a correr", "vos": "estais a correr", "eles": "estão a correr"]), level: 14),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Doing right now", conjugations: .init(br: ["eu": "estou fazendo", "voce": "está fazendo", "nos": "estamos fazendo", "voces": "estão fazendo", "eles": "estão fazendo"], pt: ["eu": "estou a fazer", "tu": "estás a fazer", "ele": "está a fazer", "nos": "estamos a fazer", "vos": "estais a fazer", "eles": "estão a fazer"]), level: 14),
            Verb(infinitive: "Estudar", translation: "To study", irregular: false, context: "Studying right now", conjugations: .init(br: ["eu": "estou estudando", "voce": "está estudando", "nos": "estamos estudando", "voces": "estão estudando", "eles": "estão estudando"], pt: ["eu": "estou a estudar", "tu": "estás a estudar", "ele": "está a estudar", "nos": "estamos a estudar", "vos": "estais a estudar", "eles": "estão a estudar"]), level: 14),
            Verb(infinitive: "Viajar", translation: "To travel", irregular: false, context: "Traveling right now", conjugations: .init(br: ["eu": "estou viajando", "voce": "está viajando", "nos": "estamos viajando", "voces": "estão viajando", "eles": "estão viajando"], pt: ["eu": "estou a viajar", "tu": "estás a viajar", "ele": "está a viajar", "nos": "estamos a viajar", "vos": "estais a viajar", "eles": "estão a viajar"]), level: 14)
        ]))

        // MARK: - Level 15-16: Reflexivos
        result.append(Level(level: 15, tense: "Reflexivos", verbs: [
            Verb(infinitive: "Vestir-se", translation: "To get dressed", irregular: true, context: "Getting dressed", conjugations: .init(br: ["eu": "me visto", "voce": "se veste", "nos": "nos vestimos", "voces": "se vestem", "eles": "se vestem"], pt: ["eu": "visto-me", "tu": "vestes-te", "ele": "veste-se", "nos": "vestimo-nos", "vos": "vestis-vos", "eles": "vestem-se"]), level: 15),
            Verb(infinitive: "Lavar-se", translation: "To wash oneself", irregular: false, context: "Washing up", conjugations: .init(br: ["eu": "me lavo", "voce": "se lava", "nos": "nos lavamos", "voces": "se lavam", "eles": "se lavam"], pt: ["eu": "lavo-me", "tu": "lavas-te", "ele": "lava-se", "nos": "lavamo-nos", "vos": "lavais-vos", "eles": "lavam-se"]), level: 15),
            Verb(infinitive: "Sentar-se", translation: "To sit down", irregular: false, context: "Sitting", conjugations: .init(br: ["eu": "me sento", "voce": "se senta", "nos": "nos sentamos", "voces": "se sentam", "eles": "se sentam"], pt: ["eu": "sento-me", "tu": "sentas-te", "ele": "senta-se", "nos": "sentamo-nos", "vos": "sentais-vos", "eles": "sentam-se"]), level: 15),
            Verb(infinitive: "Deitar-se", translation: "To lie down", irregular: false, context: "Going to bed", conjugations: .init(br: ["eu": "me deito", "voce": "se deita", "nos": "nos deitamos", "voces": "se deitam", "eles": "se deitam"], pt: ["eu": "deito-me", "tu": "deitas-te", "ele": "deita-se", "nos": "deitamo-nos", "vos": "deitais-vos", "eles": "deitam-se"]), level: 15),
            Verb(infinitive: "Levantar-se", translation: "To get up", irregular: false, context: "Waking up", conjugations: .init(br: ["eu": "me levanto", "voce": "se levanta", "nos": "nos levantamos", "voces": "se levantam", "eles": "se levantam"], pt: ["eu": "levanto-me", "tu": "levantas-te", "ele": "levanta-se", "nos": "levantamo-nos", "vos": "levantais-vos", "eles": "levantam-se"]), level: 15)
        ]))

        result.append(Level(level: 16, tense: "Reflexivos", verbs: [
            Verb(infinitive: "Chamar-se", translation: "To be called", irregular: false, context: "Introductions", conjugations: .init(br: ["eu": "me chamo", "voce": "se chama", "nos": "nos chamamos", "voces": "se chamam", "eles": "se chamam"], pt: ["eu": "chamo-me", "tu": "chamas-te", "ele": "chama-se", "nos": "chamamo-nos", "vos": "chamais-vos", "eles": "chamam-se"]), level: 16),
            Verb(infinitive: "Lembrar-se", translation: "To remember", irregular: false, context: "Remembering", conjugations: .init(br: ["eu": "me lembro", "voce": "se lembra", "nos": "nos lembramos", "voces": "se lembram", "eles": "se lembram"], pt: ["eu": "lembro-me", "tu": "lembras-te", "ele": "lembra-se", "nos": "lembramo-nos", "vos": "lembrais-vos", "eles": "lembram-se"]), level: 16),
            Verb(infinitive: "Divertir-se", translation: "To have fun", irregular: true, context: "Enjoying oneself", conjugations: .init(br: ["eu": "me divirto", "voce": "se diverte", "nos": "nos divertimos", "voces": "se divertem", "eles": "se divertem"], pt: ["eu": "divirto-me", "tu": "divertes-te", "ele": "diverte-se", "nos": "divertimo-nos", "vos": "divertis-vos", "eles": "divertem-se"]), level: 16),
            Verb(infinitive: "Preocupar-se", translation: "To worry", irregular: false, context: "Worrying", conjugations: .init(br: ["eu": "me preocupo", "voce": "se preocupa", "nos": "nos preocupamos", "voces": "se preocupam", "eles": "se preocupam"], pt: ["eu": "preocupo-me", "tu": "preocupas-te", "ele": "preocupa-se", "nos": "preocupamo-nos", "vos": "preocupais-vos", "eles": "preocupam-se"]), level: 16)
        ]))

        // MARK: - Levels 17-22: Pretérito Perfeito
        result.append(Level(level: 17, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Spoke in the past", conjugations: .init(br: ["eu": "falei", "voce": "falou", "nos": "falamos", "voces": "falaram", "eles": "falaram"], pt: ["eu": "falei", "tu": "falaste", "ele": "falou", "nos": "falámos", "vos": "falastes", "eles": "falaram"]), level: 17),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Ate in the past", conjugations: .init(br: ["eu": "comi", "voce": "comeu", "nos": "comemos", "voces": "comeram", "eles": "comeram"], pt: ["eu": "comi", "tu": "comeste", "ele": "comeu", "nos": "comemos", "vos": "comestes", "eles": "comeram"]), level: 17),
            Verb(infinitive: "Partir", translation: "To leave", irregular: false, context: "Left in the past", conjugations: .init(br: ["eu": "parti", "voce": "partiu", "nos": "partimos", "voces": "partiram", "eles": "partiram"], pt: ["eu": "parti", "tu": "partiste", "ele": "partiu", "nos": "partimos", "vos": "partistes", "eles": "partiram"]), level: 17),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Worked in the past", conjugations: .init(br: ["eu": "trabalhei", "voce": "trabalhou", "nos": "trabalhamos", "voces": "trabalharam", "eles": "trabalharam"], pt: ["eu": "trabalhei", "tu": "trabalhaste", "ele": "trabalhou", "nos": "trabalhámos", "vos": "trabalhastes", "eles": "trabalharam"]), level: 17),
            Verb(infinitive: "Estudar", translation: "To study", irregular: false, context: "Studied in the past", conjugations: .init(br: ["eu": "estudei", "voce": "estudou", "nos": "estudamos", "voces": "estudaram", "eles": "estudaram"], pt: ["eu": "estudei", "tu": "estudaste", "ele": "estudou", "nos": "estudámos", "vos": "estudastes", "eles": "estudaram"]), level: 17)
        ]))

        result.append(Level(level: 18, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "Was (permanent)", conjugations: .init(br: ["eu": "fui", "voce": "foi", "nos": "fomos", "voces": "foram", "eles": "foram"], pt: ["eu": "fui", "tu": "foste", "ele": "foi", "nos": "fomos", "vos": "fostes", "eles": "foram"]), level: 18),
            Verb(infinitive: "Estar", translation: "To be", irregular: true, context: "Was (temporary)", conjugations: .init(br: ["eu": "estive", "voce": "esteve", "nos": "estivemos", "voces": "estiveram", "eles": "estiveram"], pt: ["eu": "estive", "tu": "estiveste", "ele": "esteve", "nos": "estivemos", "vos": "estivestes", "eles": "estiveram"]), level: 18),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Had", conjugations: .init(br: ["eu": "tive", "voce": "teve", "nos": "tivemos", "voces": "tiveram", "eles": "tiveram"], pt: ["eu": "tive", "tu": "tiveste", "ele": "teve", "nos": "tivemos", "vos": "tivestes", "eles": "tiveram"]), level: 18),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Went", conjugations: .init(br: ["eu": "fui", "voce": "foi", "nos": "fomos", "voces": "foram", "eles": "foram"], pt: ["eu": "fui", "tu": "foste", "ele": "foi", "nos": "fomos", "vos": "fostes", "eles": "foram"]), level: 18)
        ]))

        result.append(Level(level: 19, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Did/made", conjugations: .init(br: ["eu": "fiz", "voce": "fez", "nos": "fizemos", "voces": "fizeram", "eles": "fizeram"], pt: ["eu": "fiz", "tu": "fizeste", "ele": "fez", "nos": "fizemos", "vos": "fizestes", "eles": "fizeram"]), level: 19),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "Said", conjugations: .init(br: ["eu": "disse", "voce": "disse", "nos": "dissemos", "voces": "disseram", "eles": "disseram"], pt: ["eu": "disse", "tu": "disseste", "ele": "disse", "nos": "dissemos", "vos": "dissestes", "eles": "disseram"]), level: 19),
            Verb(infinitive: "Trazer", translation: "To bring", irregular: true, context: "Brought", conjugations: .init(br: ["eu": "trouxe", "voce": "trouxe", "nos": "trouxemos", "voces": "trouxeram", "eles": "trouxeram"], pt: ["eu": "trouxe", "tu": "trouxeste", "ele": "trouxe", "nos": "trouxemos", "vos": "trouxestes", "eles": "trouxeram"]), level: 19),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "Could", conjugations: .init(br: ["eu": "pude", "voce": "pôde", "nos": "pudemos", "voces": "puderam", "eles": "puderam"], pt: ["eu": "pude", "tu": "pudeste", "ele": "pôde", "nos": "pudemos", "vos": "pudestes", "eles": "puderam"]), level: 19),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "Found out", conjugations: .init(br: ["eu": "soube", "voce": "soube", "nos": "soubemos", "voces": "souberam", "eles": "souberam"], pt: ["eu": "soube", "tu": "soubeste", "ele": "soube", "nos": "soubemos", "vos": "soubestes", "eles": "souberam"]), level: 19)
        ]))

        result.append(Level(level: 20, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "Gave", conjugations: .init(br: ["eu": "dei", "voce": "deu", "nos": "demos", "voces": "deram", "eles": "deram"], pt: ["eu": "dei", "tu": "deste", "ele": "deu", "nos": "demos", "vos": "destes", "eles": "deram"]), level: 20),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "Saw", conjugations: .init(br: ["eu": "vi", "voce": "viu", "nos": "vimos", "voces": "viram", "eles": "viram"], pt: ["eu": "vi", "tu": "viste", "ele": "viu", "nos": "vimos", "vos": "vistes", "eles": "viram"]), level: 20),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "Came", conjugations: .init(br: ["eu": "vim", "voce": "veio", "nos": "viemos", "voces": "vieram", "eles": "vieram"], pt: ["eu": "vim", "tu": "vieste", "ele": "veio", "nos": "viemos", "vos": "viestes", "eles": "vieram"]), level: 20),
            Verb(infinitive: "Pôr", translation: "To put", irregular: true, context: "Put/placed", conjugations: .init(br: ["eu": "pus", "voce": "pôs", "nos": "pusemos", "voces": "puseram", "eles": "puseram"], pt: ["eu": "pus", "tu": "puseste", "ele": "pôs", "nos": "pusemos", "vos": "pusestes", "eles": "puseram"]), level: 20),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "Wanted", conjugations: .init(br: ["eu": "quis", "voce": "quis", "nos": "quisemos", "voces": "quiseram", "eles": "quiseram"], pt: ["eu": "quis", "tu": "quiseste", "ele": "quis", "nos": "quisemos", "vos": "quisestes", "eles": "quiseram"]), level: 20)
        ]))

        result.append(Level(level: 21, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Comprar", translation: "To buy", irregular: false, context: "Bought", conjugations: .init(br: ["eu": "comprei", "voce": "comprou", "nos": "compramos", "voces": "compraram", "eles": "compraram"], pt: ["eu": "comprei", "tu": "compraste", "ele": "comprou", "nos": "comprámos", "vos": "comprastes", "eles": "compraram"]), level: 21),
            Verb(infinitive: "Vender", translation: "To sell", irregular: false, context: "Sold", conjugations: .init(br: ["eu": "vendi", "voce": "vendeu", "nos": "vendemos", "voces": "venderam", "eles": "venderam"], pt: ["eu": "vendi", "tu": "vendeste", "ele": "vendeu", "nos": "vendemos", "vos": "vendestes", "eles": "venderam"]), level: 21),
            Verb(infinitive: "Abrir", translation: "To open", irregular: false, context: "Opened", conjugations: .init(br: ["eu": "abri", "voce": "abriu", "nos": "abrimos", "voces": "abriram", "eles": "abriram"], pt: ["eu": "abri", "tu": "abriste", "ele": "abriu", "nos": "abrimos", "vos": "abristes", "eles": "abriram"]), level: 21),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "Wrote", conjugations: .init(br: ["eu": "escrevi", "voce": "escreveu", "nos": "escrevemos", "voces": "escreveram", "eles": "escreveram"], pt: ["eu": "escrevi", "tu": "escreveste", "ele": "escreveu", "nos": "escrevemos", "vos": "escrevestes", "eles": "escreveram"]), level: 21),
            Verb(infinitive: "Decidir", translation: "To decide", irregular: false, context: "Decided", conjugations: .init(br: ["eu": "decidi", "voce": "decidiu", "nos": "decidimos", "voces": "decidiram", "eles": "decidiram"], pt: ["eu": "decidi", "tu": "decidiste", "ele": "decidiu", "nos": "decidimos", "vos": "decidistes", "eles": "decidiram"]), level: 21)
        ]))

        result.append(Level(level: 22, tense: "Pretérito Perfeito", verbs: [
            Verb(infinitive: "Pedir", translation: "To ask for", irregular: true, context: "Asked for", conjugations: .init(br: ["eu": "pedi", "voce": "pediu", "nos": "pedimos", "voces": "pediram", "eles": "pediram"], pt: ["eu": "pedi", "tu": "pediste", "ele": "pediu", "nos": "pedimos", "vos": "pedistes", "eles": "pediram"]), level: 22),
            Verb(infinitive: "Ouvir", translation: "To hear", irregular: true, context: "Heard", conjugations: .init(br: ["eu": "ouvi", "voce": "ouviu", "nos": "ouvimos", "voces": "ouviram", "eles": "ouviram"], pt: ["eu": "ouvi", "tu": "ouviste", "ele": "ouviu", "nos": "ouvimos", "vos": "ouvistes", "eles": "ouviram"]), level: 22),
            Verb(infinitive: "Dormir", translation: "To sleep", irregular: true, context: "Slept", conjugations: .init(br: ["eu": "dormi", "voce": "dormiu", "nos": "dormimos", "voces": "dormiram", "eles": "dormiram"], pt: ["eu": "dormi", "tu": "dormiste", "ele": "dormiu", "nos": "dormimos", "vos": "dormistes", "eles": "dormiram"]), level: 22),
            Verb(infinitive: "Sentir", translation: "To feel", irregular: true, context: "Felt", conjugations: .init(br: ["eu": "senti", "voce": "sentiu", "nos": "sentimos", "voces": "sentiram", "eles": "sentiram"], pt: ["eu": "senti", "tu": "sentiste", "ele": "sentiu", "nos": "sentimos", "vos": "sentistes", "eles": "sentiram"]), level: 22),
            Verb(infinitive: "Conseguir", translation: "To achieve", irregular: true, context: "Managed to", conjugations: .init(br: ["eu": "consegui", "voce": "conseguiu", "nos": "conseguimos", "voces": "conseguiram", "eles": "conseguiram"], pt: ["eu": "consegui", "tu": "conseguiste", "ele": "conseguiu", "nos": "conseguimos", "vos": "conseguistes", "eles": "conseguiram"]), level: 22)
        ]))

        // MARK: - Levels 23-26: Pretérito Imperfeito
        result.append(Level(level: 23, tense: "Pretérito Imperfeito", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Used to speak", conjugations: .init(br: ["eu": "falava", "voce": "falava", "nos": "falávamos", "voces": "falavam", "eles": "falavam"], pt: ["eu": "falava", "tu": "falavas", "ele": "falava", "nos": "falávamos", "vos": "faláveis", "eles": "falavam"]), level: 23),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Used to eat", conjugations: .init(br: ["eu": "comia", "voce": "comia", "nos": "comíamos", "voces": "comiam", "eles": "comiam"], pt: ["eu": "comia", "tu": "comias", "ele": "comia", "nos": "comíamos", "vos": "comíeis", "eles": "comiam"]), level: 23),
            Verb(infinitive: "Morar", translation: "To live", irregular: false, context: "Used to live", conjugations: .init(br: ["eu": "morava", "voce": "morava", "nos": "morávamos", "voces": "moravam", "eles": "moravam"], pt: ["eu": "morava", "tu": "moravas", "ele": "morava", "nos": "morávamos", "vos": "moráveis", "eles": "moravam"]), level: 23),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Used to work", conjugations: .init(br: ["eu": "trabalhava", "voce": "trabalhava", "nos": "trabalhávamos", "voces": "trabalhavam", "eles": "trabalhavam"], pt: ["eu": "trabalhava", "tu": "trabalhavas", "ele": "trabalhava", "nos": "trabalhávamos", "vos": "trabalháveis", "eles": "trabalhavam"]), level: 23),
            Verb(infinitive: "Estudar", translation: "To study", irregular: false, context: "Used to study", conjugations: .init(br: ["eu": "estudava", "voce": "estudava", "nos": "estudávamos", "voces": "estudavam", "eles": "estudavam"], pt: ["eu": "estudava", "tu": "estudavas", "ele": "estudava", "nos": "estudávamos", "vos": "estudáveis", "eles": "estudavam"]), level: 23)
        ]))

        result.append(Level(level: 24, tense: "Pretérito Imperfeito", verbs: [
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "Used to be", conjugations: .init(br: ["eu": "era", "voce": "era", "nos": "éramos", "voces": "eram", "eles": "eram"], pt: ["eu": "era", "tu": "eras", "ele": "era", "nos": "éramos", "vos": "éreis", "eles": "eram"]), level: 24),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Used to have", conjugations: .init(br: ["eu": "tinha", "voce": "tinha", "nos": "tínhamos", "voces": "tinham", "eles": "tinham"], pt: ["eu": "tinha", "tu": "tinhas", "ele": "tinha", "nos": "tínhamos", "vos": "tínheis", "eles": "tinham"]), level: 24),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Used to go", conjugations: .init(br: ["eu": "ia", "voce": "ia", "nos": "íamos", "voces": "iam", "eles": "iam"], pt: ["eu": "ia", "tu": "ias", "ele": "ia", "nos": "íamos", "vos": "íeis", "eles": "iam"]), level: 24),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "Used to come", conjugations: .init(br: ["eu": "vinha", "voce": "vinha", "nos": "vínhamos", "voces": "vinham", "eles": "vinham"], pt: ["eu": "vinha", "tu": "vinhas", "ele": "vinha", "nos": "vínhamos", "vos": "vínheis", "eles": "vinham"]), level: 24),
            Verb(infinitive: "Pôr", translation: "To put", irregular: true, context: "Used to put", conjugations: .init(br: ["eu": "punha", "voce": "punha", "nos": "púnhamos", "voces": "punham", "eles": "punham"], pt: ["eu": "punha", "tu": "punhas", "ele": "punha", "nos": "púnhamos", "vos": "púnheis", "eles": "punham"]), level: 24)
        ]))

        result.append(Level(level: 25, tense: "Pretérito Imperfeito", verbs: [
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Used to do", conjugations: .init(br: ["eu": "fazia", "voce": "fazia", "nos": "fazíamos", "voces": "faziam", "eles": "faziam"], pt: ["eu": "fazia", "tu": "fazias", "ele": "fazia", "nos": "fazíamos", "vos": "fazíeis", "eles": "faziam"]), level: 25),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "Used to say", conjugations: .init(br: ["eu": "dizia", "voce": "dizia", "nos": "dizíamos", "voces": "diziam", "eles": "diziam"], pt: ["eu": "dizia", "tu": "dizias", "ele": "dizia", "nos": "dizíamos", "vos": "dizíeis", "eles": "diziam"]), level: 25),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "Used to want", conjugations: .init(br: ["eu": "queria", "voce": "queria", "nos": "queríamos", "voces": "queriam", "eles": "queriam"], pt: ["eu": "queria", "tu": "querias", "ele": "queria", "nos": "queríamos", "vos": "queríeis", "eles": "queriam"]), level: 25),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "Used to be able", conjugations: .init(br: ["eu": "podia", "voce": "podia", "nos": "podíamos", "voces": "podiam", "eles": "podiam"], pt: ["eu": "podia", "tu": "podias", "ele": "podia", "nos": "podíamos", "vos": "podíeis", "eles": "podiam"]), level: 25),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "Used to know", conjugations: .init(br: ["eu": "sabia", "voce": "sabia", "nos": "sabíamos", "voces": "sabiam", "eles": "sabiam"], pt: ["eu": "sabia", "tu": "sabias", "ele": "sabia", "nos": "sabíamos", "vos": "sabíeis", "eles": "sabiam"]), level: 25)
        ]))

        result.append(Level(level: 26, tense: "Pretérito Imperfeito", verbs: [
            Verb(infinitive: "Dormir", translation: "To sleep", irregular: true, context: "Used to sleep", conjugations: .init(br: ["eu": "dormia", "voce": "dormia", "nos": "dormíamos", "voces": "dormiam", "eles": "dormiam"], pt: ["eu": "dormia", "tu": "dormias", "ele": "dormia", "nos": "dormíamos", "vos": "dormíeis", "eles": "dormiam"]), level: 26),
            Verb(infinitive: "Ler", translation: "To read", irregular: true, context: "Used to read", conjugations: .init(br: ["eu": "lia", "voce": "lia", "nos": "líamos", "voces": "liam", "eles": "liam"], pt: ["eu": "lia", "tu": "lias", "ele": "lia", "nos": "líamos", "vos": "líeis", "eles": "liam"]), level: 26),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "Used to see", conjugations: .init(br: ["eu": "via", "voce": "via", "nos": "víamos", "voces": "viam", "eles": "viam"], pt: ["eu": "via", "tu": "vias", "ele": "via", "nos": "víamos", "vos": "víeis", "eles": "viam"]), level: 26),
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "Used to give", conjugations: .init(br: ["eu": "dava", "voce": "dava", "nos": "dávamos", "voces": "davam", "eles": "davam"], pt: ["eu": "dava", "tu": "davas", "ele": "dava", "nos": "dávamos", "vos": "dáveis", "eles": "davam"]), level: 26),
            Verb(infinitive: "Gostar", translation: "To like", irregular: false, context: "Used to like", conjugations: .init(br: ["eu": "gostava", "voce": "gostava", "nos": "gostávamos", "voces": "gostavam", "eles": "gostavam"], pt: ["eu": "gostava", "tu": "gostavas", "ele": "gostava", "nos": "gostávamos", "vos": "gostáveis", "eles": "gostavam"]), level: 26)
        ]))

        // MARK: - Levels 27-29: Futuro
        result.append(Level(level: 27, tense: "Futuro", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Will speak", conjugations: .init(br: ["eu": "falarei", "voce": "falará", "nos": "falaremos", "voces": "falarão", "eles": "falarão"], pt: ["eu": "falarei", "tu": "falarás", "ele": "falará", "nos": "falaremos", "vos": "falareis", "eles": "falarão"]), level: 27),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Will eat", conjugations: .init(br: ["eu": "comerei", "voce": "comerá", "nos": "comeremos", "voces": "comerão", "eles": "comerão"], pt: ["eu": "comerei", "tu": "comerás", "ele": "comerá", "nos": "comeremos", "vos": "comereis", "eles": "comerão"]), level: 27),
            Verb(infinitive: "Partir", translation: "To leave", irregular: false, context: "Will leave", conjugations: .init(br: ["eu": "partirei", "voce": "partirá", "nos": "partiremos", "voces": "partirão", "eles": "partirão"], pt: ["eu": "partirei", "tu": "partirás", "ele": "partirá", "nos": "partiremos", "vos": "partireis", "eles": "partirão"]), level: 27),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "Will work", conjugations: .init(br: ["eu": "trabalharei", "voce": "trabalhará", "nos": "trabalharemos", "voces": "trabalharão", "eles": "trabalharão"], pt: ["eu": "trabalharei", "tu": "trabalharás", "ele": "trabalhará", "nos": "trabalharemos", "vos": "trabalhareis", "eles": "trabalharão"]), level: 27),
            Verb(infinitive: "Viajar", translation: "To travel", irregular: false, context: "Will travel", conjugations: .init(br: ["eu": "viajarei", "voce": "viajará", "nos": "viajaremos", "voces": "viajarão", "eles": "viajarão"], pt: ["eu": "viajarei", "tu": "viajarás", "ele": "viajará", "nos": "viajaremos", "vos": "viajareis", "eles": "viajarão"]), level: 27)
        ]))

        result.append(Level(level: 28, tense: "Futuro", verbs: [
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "Will be", conjugations: .init(br: ["eu": "serei", "voce": "será", "nos": "seremos", "voces": "serão", "eles": "serão"], pt: ["eu": "serei", "tu": "serás", "ele": "será", "nos": "seremos", "vos": "sereis", "eles": "serão"]), level: 28),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Will have", conjugations: .init(br: ["eu": "terei", "voce": "terá", "nos": "teremos", "voces": "terão", "eles": "terão"], pt: ["eu": "terei", "tu": "terás", "ele": "terá", "nos": "teremos", "vos": "tereis", "eles": "terão"]), level: 28),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Will do", conjugations: .init(br: ["eu": "farei", "voce": "fará", "nos": "faremos", "voces": "farão", "eles": "farão"], pt: ["eu": "farei", "tu": "farás", "ele": "fará", "nos": "faremos", "vos": "fareis", "eles": "farão"]), level: 28),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "Will say", conjugations: .init(br: ["eu": "direi", "voce": "dirá", "nos": "diremos", "voces": "dirão", "eles": "dirão"], pt: ["eu": "direi", "tu": "dirás", "ele": "dirá", "nos": "diremos", "vos": "direis", "eles": "dirão"]), level: 28),
            Verb(infinitive: "Trazer", translation: "To bring", irregular: true, context: "Will bring", conjugations: .init(br: ["eu": "trarei", "voce": "trará", "nos": "traremos", "voces": "trarão", "eles": "trarão"], pt: ["eu": "trarei", "tu": "trarás", "ele": "trará", "nos": "traremos", "vos": "trareis", "eles": "trarão"]), level: 28)
        ]))

        result.append(Level(level: 29, tense: "Futuro", verbs: [
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "Will be able", conjugations: .init(br: ["eu": "poderei", "voce": "poderá", "nos": "poderemos", "voces": "poderão", "eles": "poderão"], pt: ["eu": "poderei", "tu": "poderás", "ele": "poderá", "nos": "poderemos", "vos": "podereis", "eles": "poderão"]), level: 29),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "Will want", conjugations: .init(br: ["eu": "quererei", "voce": "quererá", "nos": "quereremos", "voces": "quererão", "eles": "quererão"], pt: ["eu": "quererei", "tu": "quererás", "ele": "quererá", "nos": "quereremos", "vos": "querereis", "eles": "quererão"]), level: 29),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "Will know", conjugations: .init(br: ["eu": "saberei", "voce": "saberá", "nos": "saberemos", "voces": "saberão", "eles": "saberão"], pt: ["eu": "saberei", "tu": "saberás", "ele": "saberá", "nos": "saberemos", "vos": "sabereis", "eles": "saberão"]), level: 29),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "Will see", conjugations: .init(br: ["eu": "verei", "voce": "verá", "nos": "veremos", "voces": "verão", "eles": "verão"], pt: ["eu": "verei", "tu": "verás", "ele": "verá", "nos": "veremos", "vos": "vereis", "eles": "verão"]), level: 29),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Will go", conjugations: .init(br: ["eu": "irei", "voce": "irá", "nos": "iremos", "voces": "irão", "eles": "irão"], pt: ["eu": "irei", "tu": "irás", "ele": "irá", "nos": "iremos", "vos": "ireis", "eles": "irão"]), level: 29)
        ]))

        // MARK: - Levels 30-31: Condicional
        result.append(Level(level: 30, tense: "Condicional", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Would speak", conjugations: .init(br: ["eu": "falaria", "voce": "falaria", "nos": "falaríamos", "voces": "falariam", "eles": "falariam"], pt: ["eu": "falaria", "tu": "falarias", "ele": "falaria", "nos": "falaríamos", "vos": "falaríeis", "eles": "falariam"]), level: 30),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Would eat", conjugations: .init(br: ["eu": "comeria", "voce": "comeria", "nos": "comeríamos", "voces": "comeriam", "eles": "comeriam"], pt: ["eu": "comeria", "tu": "comerias", "ele": "comeria", "nos": "comeríamos", "vos": "comeríeis", "eles": "comeriam"]), level: 30),
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "Would be", conjugations: .init(br: ["eu": "seria", "voce": "seria", "nos": "seríamos", "voces": "seriam", "eles": "seriam"], pt: ["eu": "seria", "tu": "serias", "ele": "seria", "nos": "seríamos", "vos": "seríeis", "eles": "seriam"]), level: 30),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Would have", conjugations: .init(br: ["eu": "teria", "voce": "teria", "nos": "teríamos", "voces": "teriam", "eles": "teriam"], pt: ["eu": "teria", "tu": "terias", "ele": "teria", "nos": "teríamos", "vos": "teríeis", "eles": "teriam"]), level: 30),
            Verb(infinitive: "Gostar", translation: "To like", irregular: false, context: "Would like", conjugations: .init(br: ["eu": "gostaria", "voce": "gostaria", "nos": "gostaríamos", "voces": "gostariam", "eles": "gostariam"], pt: ["eu": "gostaria", "tu": "gostarias", "ele": "gostaria", "nos": "gostaríamos", "vos": "gostaríeis", "eles": "gostariam"]), level: 30)
        ]))

        result.append(Level(level: 31, tense: "Condicional", verbs: [
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "Could", conjugations: .init(br: ["eu": "poderia", "voce": "poderia", "nos": "poderíamos", "voces": "poderiam", "eles": "poderiam"], pt: ["eu": "poderia", "tu": "poderias", "ele": "poderia", "nos": "poderíamos", "vos": "poderíeis", "eles": "poderiam"]), level: 31),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Would do", conjugations: .init(br: ["eu": "faria", "voce": "faria", "nos": "faríamos", "voces": "fariam", "eles": "fariam"], pt: ["eu": "faria", "tu": "farias", "ele": "faria", "nos": "faríamos", "vos": "faríeis", "eles": "fariam"]), level: 31),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "Would say", conjugations: .init(br: ["eu": "diria", "voce": "diria", "nos": "diríamos", "voces": "diriam", "eles": "diriam"], pt: ["eu": "diria", "tu": "dirias", "ele": "diria", "nos": "diríamos", "vos": "diríeis", "eles": "diriam"]), level: 31),
            Verb(infinitive: "Trazer", translation: "To bring", irregular: true, context: "Would bring", conjugations: .init(br: ["eu": "traria", "voce": "traria", "nos": "traríamos", "voces": "trariam", "eles": "trariam"], pt: ["eu": "traria", "tu": "trarias", "ele": "traria", "nos": "traríamos", "vos": "traríeis", "eles": "trariam"]), level: 31),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "Would want", conjugations: .init(br: ["eu": "quereria", "voce": "quereria", "nos": "quereríamos", "voces": "quereriam", "eles": "quereriam"], pt: ["eu": "quereria", "tu": "quererias", "ele": "quereria", "nos": "quereríamos", "vos": "quereríeis", "eles": "quereriam"]), level: 31)
        ]))

        // MARK: - Level 32: Infinitivo Pessoal
        result.append(Level(level: 32, tense: "Infinitivo Pessoal", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Personal infinitive", conjugations: .init(br: ["eu": "falar", "voce": "falar", "nos": "falarmos", "voces": "falarem", "eles": "falarem"], pt: ["eu": "falar", "tu": "falares", "ele": "falar", "nos": "falarmos", "vos": "falardes", "eles": "falarem"]), level: 32),
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "Personal infinitive", conjugations: .init(br: ["eu": "ser", "voce": "ser", "nos": "sermos", "voces": "serem", "eles": "serem"], pt: ["eu": "ser", "tu": "seres", "ele": "ser", "nos": "sermos", "vos": "serdes", "eles": "serem"]), level: 32),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Personal infinitive", conjugations: .init(br: ["eu": "fazer", "voce": "fazer", "nos": "fazermos", "voces": "fazerem", "eles": "fazerem"], pt: ["eu": "fazer", "tu": "fazeres", "ele": "fazer", "nos": "fazermos", "vos": "fazerdes", "eles": "fazerem"]), level: 32),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Personal infinitive", conjugations: .init(br: ["eu": "ter", "voce": "ter", "nos": "termos", "voces": "terem", "eles": "terem"], pt: ["eu": "ter", "tu": "teres", "ele": "ter", "nos": "termos", "vos": "terdes", "eles": "terem"]), level: 32),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "Personal infinitive", conjugations: .init(br: ["eu": "saber", "voce": "saber", "nos": "sabermos", "voces": "saberem", "eles": "saberem"], pt: ["eu": "saber", "tu": "saberes", "ele": "saber", "nos": "sabermos", "vos": "saberdes", "eles": "saberem"]), level: 32)
        ]))

        // MARK: - Levels 33-36: Presente do Subjuntivo
        result.append(Level(level: 33, tense: "Presente do Subjuntivo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "That I speak", conjugations: .init(br: ["eu": "fale", "voce": "fale", "nos": "falemos", "voces": "falem", "eles": "falem"], pt: ["eu": "fale", "tu": "fales", "ele": "fale", "nos": "falemos", "vos": "faleis", "eles": "falem"]), level: 33),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "That I eat", conjugations: .init(br: ["eu": "coma", "voce": "coma", "nos": "comamos", "voces": "comam", "eles": "comam"], pt: ["eu": "coma", "tu": "comas", "ele": "coma", "nos": "comamos", "vos": "comais", "eles": "comam"]), level: 33),
            Verb(infinitive: "Partir", translation: "To leave", irregular: false, context: "That I leave", conjugations: .init(br: ["eu": "parta", "voce": "parta", "nos": "partamos", "voces": "partam", "eles": "partam"], pt: ["eu": "parta", "tu": "partas", "ele": "parta", "nos": "partamos", "vos": "partais", "eles": "partam"]), level: 33),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "That I work", conjugations: .init(br: ["eu": "trabalhe", "voce": "trabalhe", "nos": "trabalhemos", "voces": "trabalhem", "eles": "trabalhem"], pt: ["eu": "trabalhe", "tu": "trabalhes", "ele": "trabalhe", "nos": "trabalhemos", "vos": "trabalheis", "eles": "trabalhem"]), level: 33),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "That I write", conjugations: .init(br: ["eu": "escreva", "voce": "escreva", "nos": "escrevamos", "voces": "escrevam", "eles": "escrevam"], pt: ["eu": "escreva", "tu": "escrevas", "ele": "escreva", "nos": "escrevamos", "vos": "escrevais", "eles": "escrevam"]), level: 33)
        ]))

        result.append(Level(level: 34, tense: "Presente do Subjuntivo", verbs: [
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "That I be", conjugations: .init(br: ["eu": "seja", "voce": "seja", "nos": "sejamos", "voces": "sejam", "eles": "sejam"], pt: ["eu": "seja", "tu": "sejas", "ele": "seja", "nos": "sejamos", "vos": "sejais", "eles": "sejam"]), level: 34),
            Verb(infinitive: "Estar", translation: "To be", irregular: true, context: "That I be (state)", conjugations: .init(br: ["eu": "esteja", "voce": "esteja", "nos": "estejamos", "voces": "estejam", "eles": "estejam"], pt: ["eu": "esteja", "tu": "estejas", "ele": "esteja", "nos": "estejamos", "vos": "estejais", "eles": "estejam"]), level: 34),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "That I have", conjugations: .init(br: ["eu": "tenha", "voce": "tenha", "nos": "tenhamos", "voces": "tenham", "eles": "tenham"], pt: ["eu": "tenha", "tu": "tenhas", "ele": "tenha", "nos": "tenhamos", "vos": "tenhais", "eles": "tenham"]), level: 34),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "That I go", conjugations: .init(br: ["eu": "vá", "voce": "vá", "nos": "vamos", "voces": "vão", "eles": "vão"], pt: ["eu": "vá", "tu": "vás", "ele": "vá", "nos": "vamos", "vos": "vades", "eles": "vão"]), level: 34),
            Verb(infinitive: "Haver", translation: "To exist", irregular: true, context: "That there be", conjugations: .init(br: ["eu": "haja", "voce": "haja", "nos": "hajamos", "voces": "hajam", "eles": "hajam"], pt: ["eu": "haja", "tu": "hajas", "ele": "haja", "nos": "hajamos", "vos": "hajais", "eles": "hajam"]), level: 34)
        ]))

        result.append(Level(level: 35, tense: "Presente do Subjuntivo", verbs: [
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "That I do", conjugations: .init(br: ["eu": "faça", "voce": "faça", "nos": "façamos", "voces": "façam", "eles": "façam"], pt: ["eu": "faça", "tu": "faças", "ele": "faça", "nos": "façamos", "vos": "façais", "eles": "façam"]), level: 35),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "That I can", conjugations: .init(br: ["eu": "possa", "voce": "possa", "nos": "possamos", "voces": "possam", "eles": "possam"], pt: ["eu": "possa", "tu": "possas", "ele": "possa", "nos": "possamos", "vos": "possais", "eles": "possam"]), level: 35),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "That I know", conjugations: .init(br: ["eu": "saiba", "voce": "saiba", "nos": "saibamos", "voces": "saibam", "eles": "saibam"], pt: ["eu": "saiba", "tu": "saibas", "ele": "saiba", "nos": "saibamos", "vos": "saibais", "eles": "saibam"]), level: 35),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "That I want", conjugations: .init(br: ["eu": "queira", "voce": "queira", "nos": "queiramos", "voces": "queiram", "eles": "queiram"], pt: ["eu": "queira", "tu": "queiras", "ele": "queira", "nos": "queiramos", "vos": "queirais", "eles": "queiram"]), level: 35),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "That I say", conjugations: .init(br: ["eu": "diga", "voce": "diga", "nos": "digamos", "voces": "digam", "eles": "digam"], pt: ["eu": "diga", "tu": "digas", "ele": "diga", "nos": "digamos", "vos": "digais", "eles": "digam"]), level: 35)
        ]))

        result.append(Level(level: 36, tense: "Presente do Subjuntivo", verbs: [
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "That I give", conjugations: .init(br: ["eu": "dê", "voce": "dê", "nos": "demos", "voces": "deem", "eles": "deem"], pt: ["eu": "dê", "tu": "dês", "ele": "dê", "nos": "demos", "vos": "deis", "eles": "deem"]), level: 36),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "That I see", conjugations: .init(br: ["eu": "veja", "voce": "veja", "nos": "vejamos", "voces": "vejam", "eles": "vejam"], pt: ["eu": "veja", "tu": "vejas", "ele": "veja", "nos": "vejamos", "vos": "vejais", "eles": "vejam"]), level: 36),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "That I come", conjugations: .init(br: ["eu": "venha", "voce": "venha", "nos": "venhamos", "voces": "venham", "eles": "venham"], pt: ["eu": "venha", "tu": "venhas", "ele": "venha", "nos": "venhamos", "vos": "venhais", "eles": "venham"]), level: 36),
            Verb(infinitive: "Pôr", translation: "To put", irregular: true, context: "That I put", conjugations: .init(br: ["eu": "ponha", "voce": "ponha", "nos": "ponhamos", "voces": "ponham", "eles": "ponham"], pt: ["eu": "ponha", "tu": "ponhas", "ele": "ponha", "nos": "ponhamos", "vos": "ponhais", "eles": "ponham"]), level: 36),
            Verb(infinitive: "Trazer", translation: "To bring", irregular: true, context: "That I bring", conjugations: .init(br: ["eu": "traga", "voce": "traga", "nos": "tragamos", "voces": "tragam", "eles": "tragam"], pt: ["eu": "traga", "tu": "tragas", "ele": "traga", "nos": "tragamos", "vos": "tragais", "eles": "tragam"]), level: 36)
        ]))

        // MARK: - Level 37: Futuro do Subjuntivo
        result.append(Level(level: 37, tense: "Futuro do Subjuntivo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "When I speak", conjugations: .init(br: ["eu": "falar", "voce": "falar", "nos": "falarmos", "voces": "falarem", "eles": "falarem"], pt: ["eu": "falar", "tu": "falares", "ele": "falar", "nos": "falarmos", "vos": "falardes", "eles": "falarem"]), level: 37),
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "When I am", conjugations: .init(br: ["eu": "for", "voce": "for", "nos": "formos", "voces": "forem", "eles": "forem"], pt: ["eu": "for", "tu": "fores", "ele": "for", "nos": "formos", "vos": "fordes", "eles": "forem"]), level: 37),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "When I have", conjugations: .init(br: ["eu": "tiver", "voce": "tiver", "nos": "tivermos", "voces": "tiverem", "eles": "tiverem"], pt: ["eu": "tiver", "tu": "tiveres", "ele": "tiver", "nos": "tivermos", "vos": "tiverdes", "eles": "tiverem"]), level: 37),
            Verb(infinitive: "Fazer", translation: "To do", irregular: true, context: "When I do", conjugations: .init(br: ["eu": "fizer", "voce": "fizer", "nos": "fizermos", "voces": "fizerem", "eles": "fizerem"], pt: ["eu": "fizer", "tu": "fizeres", "ele": "fizer", "nos": "fizermos", "vos": "fizerdes", "eles": "fizerem"]), level: 37),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "When I can", conjugations: .init(br: ["eu": "puder", "voce": "puder", "nos": "pudermos", "voces": "puderem", "eles": "puderem"], pt: ["eu": "puder", "tu": "puderes", "ele": "puder", "nos": "pudermos", "vos": "puderdes", "eles": "puderem"]), level: 37),
            Verb(infinitive: "Querer", translation: "To want", irregular: true, context: "When I want", conjugations: .init(br: ["eu": "quiser", "voce": "quiser", "nos": "quisermos", "voces": "quiserem", "eles": "quiserem"], pt: ["eu": "quiser", "tu": "quiseres", "ele": "quiser", "nos": "quisermos", "vos": "quiserdes", "eles": "quiserem"]), level: 37)
        ]))

        // MARK: - Levels 38-40: Imperfeito do Subjuntivo
        result.append(Level(level: 38, tense: "Imperfeito do Subjuntivo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "If I spoke", conjugations: .init(br: ["eu": "falasse", "voce": "falasse", "nos": "falássemos", "voces": "falassem", "eles": "falassem"], pt: ["eu": "falasse", "tu": "falasses", "ele": "falasse", "nos": "falássemos", "vos": "falásseis", "eles": "falassem"]), level: 38),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "If I ate", conjugations: .init(br: ["eu": "comesse", "voce": "comesse", "nos": "comêssemos", "voces": "comessem", "eles": "comessem"], pt: ["eu": "comesse", "tu": "comesses", "ele": "comesse", "nos": "comêssemos", "vos": "comêsseis", "eles": "comessem"]), level: 38),
            Verb(infinitive: "Partir", translation: "To leave", irregular: false, context: "If I left", conjugations: .init(br: ["eu": "partisse", "voce": "partisse", "nos": "partíssemos", "voces": "partissem", "eles": "partissem"], pt: ["eu": "partisse", "tu": "partisses", "ele": "partisse", "nos": "partíssemos", "vos": "partísseis", "eles": "partissem"]), level: 38),
            Verb(infinitive: "Trabalhar", translation: "To work", irregular: false, context: "If I worked", conjugations: .init(br: ["eu": "trabalhasse", "voce": "trabalhasse", "nos": "trabalhássemos", "voces": "trabalhassem", "eles": "trabalhassem"], pt: ["eu": "trabalhasse", "tu": "trabalhasses", "ele": "trabalhasse", "nos": "trabalhássemos", "vos": "trabalhásseis", "eles": "trabalhassem"]), level: 38),
            Verb(infinitive: "Viver", translation: "To live", irregular: false, context: "If I lived", conjugations: .init(br: ["eu": "vivesse", "voce": "vivesse", "nos": "vivêssemos", "voces": "vivessem", "eles": "vivessem"], pt: ["eu": "vivesse", "tu": "vivesses", "ele": "vivesse", "nos": "vivêssemos", "vos": "vivêsseis", "eles": "vivessem"]), level: 38)
        ]))

        result.append(Level(level: 39, tense: "Imperfeito do Subjuntivo", verbs: [
            Verb(infinitive: "Ser", translation: "To be", irregular: true, context: "If I were", conjugations: .init(br: ["eu": "fosse", "voce": "fosse", "nos": "fôssemos", "voces": "fossem", "eles": "fossem"], pt: ["eu": "fosse", "tu": "fosses", "ele": "fosse", "nos": "fôssemos", "vos": "fôsseis", "eles": "fossem"]), level: 39),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "If I had", conjugations: .init(br: ["eu": "tivesse", "voce": "tivesse", "nos": "tivéssemos", "voces": "tivessem", "eles": "tivessem"], pt: ["eu": "tivesse", "tu": "tivesses", "ele": "tivesse", "nos": "tivéssemos", "vos": "tivésseis", "eles": "tivessem"]), level: 39),
            Verb(infinitive: "Fazer", translation: "To do", irregular: true, context: "If I did", conjugations: .init(br: ["eu": "fizesse", "voce": "fizesse", "nos": "fizéssemos", "voces": "fizessem", "eles": "fizessem"], pt: ["eu": "fizesse", "tu": "fizesses", "ele": "fizesse", "nos": "fizéssemos", "vos": "fizésseis", "eles": "fizessem"]), level: 39),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "If I could", conjugations: .init(br: ["eu": "pudesse", "voce": "pudesse", "nos": "pudéssemos", "voces": "pudessem", "eles": "pudessem"], pt: ["eu": "pudesse", "tu": "pudesses", "ele": "pudesse", "nos": "pudéssemos", "vos": "pudésseis", "eles": "pudessem"]), level: 39),
            Verb(infinitive: "Saber", translation: "To know", irregular: true, context: "If I knew", conjugations: .init(br: ["eu": "soubesse", "voce": "soubesse", "nos": "soubéssemos", "voces": "soubessem", "eles": "soubessem"], pt: ["eu": "soubesse", "tu": "soubesses", "ele": "soubesse", "nos": "soubéssemos", "vos": "soubésseis", "eles": "soubessem"]), level: 39)
        ]))

        result.append(Level(level: 40, tense: "Imperfeito do Subjuntivo", verbs: [
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "If I went", conjugations: .init(br: ["eu": "fosse", "voce": "fosse", "nos": "fôssemos", "voces": "fossem", "eles": "fossem"], pt: ["eu": "fosse", "tu": "fosses", "ele": "fosse", "nos": "fôssemos", "vos": "fôsseis", "eles": "fossem"]), level: 40),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "If I said", conjugations: .init(br: ["eu": "dissesse", "voce": "dissesse", "nos": "disséssemos", "voces": "dissessem", "eles": "dissessem"], pt: ["eu": "dissesse", "tu": "dissesses", "ele": "dissesse", "nos": "disséssemos", "vos": "dissésseis", "eles": "dissessem"]), level: 40),
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "If I gave", conjugations: .init(br: ["eu": "desse", "voce": "desse", "nos": "déssemos", "voces": "dessem", "eles": "dessem"], pt: ["eu": "desse", "tu": "desses", "ele": "desse", "nos": "déssemos", "vos": "désseis", "eles": "dessem"]), level: 40),
            Verb(infinitive: "Ver", translation: "To see", irregular: true, context: "If I saw", conjugations: .init(br: ["eu": "visse", "voce": "visse", "nos": "víssemos", "voces": "vissem", "eles": "vissem"], pt: ["eu": "visse", "tu": "visses", "ele": "visse", "nos": "víssemos", "vos": "vísseis", "eles": "vissem"]), level: 40),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "If I came", conjugations: .init(br: ["eu": "viesse", "voce": "viesse", "nos": "viéssemos", "voces": "viessem", "eles": "viessem"], pt: ["eu": "viesse", "tu": "viesses", "ele": "viesse", "nos": "viéssemos", "vos": "viésseis", "eles": "viessem"]), level: 40)
        ]))

        // MARK: - Levels 41-42: Imperativo
        result.append(Level(level: 41, tense: "Imperativo", verbs: [
            Verb(infinitive: "Falar", translation: "To speak", irregular: false, context: "Speak!", conjugations: .init(br: ["voce": "fale", "nos": "falemos", "voces": "falem", "eu": "—", "eles": "falem"], pt: ["tu": "fala", "voce": "fale", "nos": "falemos", "vos": "falai", "voces": "falem", "eu": "—", "eles": "falem"]), level: 41),
            Verb(infinitive: "Comer", translation: "To eat", irregular: false, context: "Eat!", conjugations: .init(br: ["voce": "coma", "nos": "comamos", "voces": "comam", "eu": "—", "eles": "comam"], pt: ["tu": "come", "voce": "coma", "nos": "comamos", "vos": "comei", "voces": "comam", "eu": "—", "eles": "comam"]), level: 41),
            Verb(infinitive: "Abrir", translation: "To open", irregular: false, context: "Open!", conjugations: .init(br: ["voce": "abra", "nos": "abramos", "voces": "abram", "eu": "—", "eles": "abram"], pt: ["tu": "abre", "voce": "abra", "nos": "abramos", "vos": "abri", "voces": "abram", "eu": "—", "eles": "abram"]), level: 41),
            Verb(infinitive: "Escrever", translation: "To write", irregular: false, context: "Write!", conjugations: .init(br: ["voce": "escreva", "nos": "escrevamos", "voces": "escrevam", "eu": "—", "eles": "escrevam"], pt: ["tu": "escreve", "voce": "escreva", "nos": "escrevamos", "vos": "escrevei", "voces": "escrevam", "eu": "—", "eles": "escrevam"]), level: 41),
            Verb(infinitive: "Olhar", translation: "To look", irregular: false, context: "Look!", conjugations: .init(br: ["voce": "olhe", "nos": "olhemos", "voces": "olhem", "eu": "—", "eles": "olhem"], pt: ["tu": "olha", "voce": "olhe", "nos": "olhemos", "vos": "olhai", "voces": "olhem", "eu": "—", "eles": "olhem"]), level: 41)
        ]))

        result.append(Level(level: 42, tense: "Imperativo", verbs: [
            Verb(infinitive: "Fazer", translation: "To do", irregular: true, context: "Do it!", conjugations: .init(br: ["voce": "faça", "nos": "façamos", "voces": "façam", "eu": "—", "eles": "façam"], pt: ["tu": "faz", "voce": "faça", "nos": "façamos", "vos": "fazei", "voces": "façam", "eu": "—", "eles": "façam"]), level: 42),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Go!", conjugations: .init(br: ["voce": "vá", "nos": "vamos", "voces": "vão", "eu": "—", "eles": "vão"], pt: ["tu": "vai", "voce": "vá", "nos": "vamos", "vos": "ide", "voces": "vão", "eu": "—", "eles": "vão"]), level: 42),
            Verb(infinitive: "Vir", translation: "To come", irregular: true, context: "Come!", conjugations: .init(br: ["voce": "venha", "nos": "venhamos", "voces": "venham", "eu": "—", "eles": "venham"], pt: ["tu": "vem", "voce": "venha", "nos": "venhamos", "vos": "vinde", "voces": "venham", "eu": "—", "eles": "venham"]), level: 42),
            Verb(infinitive: "Dar", translation: "To give", irregular: true, context: "Give!", conjugations: .init(br: ["voce": "dê", "nos": "demos", "voces": "deem", "eu": "—", "eles": "deem"], pt: ["tu": "dá", "voce": "dê", "nos": "demos", "vos": "dai", "voces": "deem", "eu": "—", "eles": "deem"]), level: 42),
            Verb(infinitive: "Dizer", translation: "To say", irregular: true, context: "Say it!", conjugations: .init(br: ["voce": "diga", "nos": "digamos", "voces": "digam", "eu": "—", "eles": "digam"], pt: ["tu": "diz", "voce": "diga", "nos": "digamos", "vos": "dizei", "voces": "digam", "eu": "—", "eles": "digam"]), level: 42)
        ]))

        // MARK: - Level 43: Revisão Final
        result.append(Level(level: 43, tense: "Revisão Final", verbs: [
            Verb(infinitive: "Ser", translation: "To be (permanent)", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "sou", "voce": "é", "nos": "somos", "voces": "são", "eles": "são"], pt: ["eu": "sou", "tu": "és", "ele": "é", "nos": "somos", "vos": "sois", "eles": "são"]), level: 43),
            Verb(infinitive: "Estar", translation: "To be (temporary)", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "estou", "voce": "está", "nos": "estamos", "voces": "estão", "eles": "estão"], pt: ["eu": "estou", "tu": "estás", "ele": "está", "nos": "estamos", "vos": "estais", "eles": "estão"]), level: 43),
            Verb(infinitive: "Ter", translation: "To have", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "tenho", "voce": "tem", "nos": "temos", "voces": "têm", "eles": "têm"], pt: ["eu": "tenho", "tu": "tens", "ele": "tem", "nos": "temos", "vos": "tendes", "eles": "têm"]), level: 43),
            Verb(infinitive: "Ir", translation: "To go", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "vou", "voce": "vai", "nos": "vamos", "voces": "vão", "eles": "vão"], pt: ["eu": "vou", "tu": "vais", "ele": "vai", "nos": "vamos", "vos": "ides", "eles": "vão"]), level: 43),
            Verb(infinitive: "Fazer", translation: "To do/make", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "faço", "voce": "faz", "nos": "fazemos", "voces": "fazem", "eles": "fazem"], pt: ["eu": "faço", "tu": "fazes", "ele": "faz", "nos": "fazemos", "vos": "fazeis", "eles": "fazem"]), level: 43),
            Verb(infinitive: "Poder", translation: "To be able", irregular: true, context: "Final review", conjugations: .init(br: ["eu": "posso", "voce": "pode", "nos": "podemos", "voces": "podem", "eles": "podem"], pt: ["eu": "posso", "tu": "podes", "ele": "pode", "nos": "podemos", "vos": "podeis", "eles": "podem"]), level: 43)
        ]))

        return result
    }
}
